import { createHash } from "node:crypto";
import { readdir, unlink } from "node:fs/promises";
import { resolve } from "node:path";
import type { AssetDefinition, CrddIr } from "./model.ts";
import type { GeneratedFile } from "./unreal.ts";

export function generateAssets(ir: CrddIr): GeneratedFile[] {
  const assets = ir.operation.assets ?? [];
  if (assets.length === 0) return [];
  return [
    ...assets.flatMap((asset) => generateBox(asset)),
    generated(
      "assets.manifest.json",
      `${JSON.stringify(
        {
          protocol: "crdd-ir/assets-v0.1",
          operation: ir.operation.id,
          scene: {
            unrealLevel: `/Game/CRDD/Generated/${ir.operation.id}Scene`,
          },
          assets: assets.map((asset) => ({
            id: asset.id,
            source: `${asset.id}.generated.obj`,
            unrealDestination: "/Game/CRDD/Generated",
            previewLevel: `/Game/CRDD/Generated/${asset.id}Level`,
            dimensionsCm: {
              length: metersToCentimeters(asset.dimensions.length.value),
              width: metersToCentimeters(asset.dimensions.width.value),
              height: metersToCentimeters(asset.dimensions.height.value),
            },
            placement: {
              locationCm: {
                x: metersToCentimeters(asset.placement.location.x.value),
                y: metersToCentimeters(asset.placement.location.y.value),
                z: metersToCentimeters(asset.placement.location.z.value),
              },
              rotationDeg: {
                pitch: asset.placement.rotation.pitch.value,
                yaw: asset.placement.rotation.yaw.value,
                roll: asset.placement.rotation.roll.value,
              },
            },
            traces: asset.traces,
          })),
        },
        null,
        2,
      )}\n`,
    ),
  ];
}

export async function removeStaleGeneratedAssets(
  outDir: string,
  expected: Set<string>,
): Promise<void> {
  const entries = await readdir(outDir, { withFileTypes: true });
  for (const entry of entries) {
    if (
      entry.isFile() &&
      (entry.name.endsWith(".generated.obj") || entry.name.endsWith(".generated.mtl")) &&
      !expected.has(entry.name)
    ) {
      const path = resolve(outDir, entry.name);
      await unlink(path);
      console.log(`Removed stale generated asset ${path}`);
    }
  }
}

function generateBox(asset: AssetDefinition): GeneratedFile[] {
  if (asset.type !== "box") throw new Error(`Unsupported 3D asset type "${asset.type}"`);
  const length = metersToCentimeters(asset.dimensions.length.value);
  const width = metersToCentimeters(asset.dimensions.width.value);
  const height = metersToCentimeters(asset.dimensions.height.value);
  const x = length / 2;
  const y = width / 2;
  const materialName = `${asset.id}Material`;
  const traces = asset.traces.map((trace) => `# CRDD-TRACE: ${trace}`).join("\n");

  const obj = `${traces}
# Generated by crdd-ir. Units: centimeters. Do not edit.
mtllib ${asset.id}.generated.mtl
o ${asset.id}
usemtl ${materialName}
v ${n(-x)} ${n(-y)} 0
v ${n(x)} ${n(-y)} 0
v ${n(x)} ${n(y)} 0
v ${n(-x)} ${n(y)} 0
v ${n(-x)} ${n(-y)} ${n(height)}
v ${n(x)} ${n(-y)} ${n(height)}
v ${n(x)} ${n(y)} ${n(height)}
v ${n(-x)} ${n(y)} ${n(height)}
vt 0 0
vt 1 0
vt 1 1
vt 0 1
f 1/1 4/4 3/3 2/2
f 5/1 6/2 7/3 8/4
f 1/1 2/2 6/3 5/4
f 2/1 3/2 7/3 6/4
f 3/1 4/2 8/3 7/4
f 4/1 1/2 5/3 8/4
`;
  const [red, green, blue] = asset.material.baseColor;
  const mtl = `${traces}
# Generated by crdd-ir. Do not edit.
newmtl ${materialName}
Ka 0 0 0
Kd ${n(red)} ${n(green)} ${n(blue)}
Ks 0 0 0
d 1
illum 1
`;

  return [
    generated(`${asset.id}.generated.obj`, obj),
    generated(`${asset.id}.generated.mtl`, mtl),
  ];
}

function generated(name: string, content: string): GeneratedFile {
  return {
    name,
    content,
    sha256: createHash("sha256").update(content).digest("hex"),
  };
}

function metersToCentimeters(value: number): number {
  return value * 100;
}

function n(value: number): string {
  return Number(value.toFixed(6)).toString();
}
