import { createHash } from "node:crypto";
import type { AssetDefinition, CrddIr } from "./model.ts";
import type { GeneratedFile } from "./unreal.ts";

export function generateAssets(ir: CrddIr): GeneratedFile[] {
  return (ir.operation.assets ?? []).flatMap((asset) => generateBox(asset));
}

function generateBox(asset: AssetDefinition): GeneratedFile[] {
  if (asset.type !== "box") throw new Error(`Unsupported 3D asset type "${asset.type}"`);
  const length = metersToCentimeters(asset.dimensions.length.value);
  const width = metersToCentimeters(asset.dimensions.width.value);
  const height = metersToCentimeters(asset.dimensions.height.value);
  const x = length / 2;
  const y = width / 2;
  const materialName = `${asset.id}Material`;
  const traces = asset.traces.map((trace) => `# CRDD-TRACE: ${trace}`).join("\n");

  const obj = `${traces}
# Generated by crdd-ir. Units: centimeters. Do not edit.
mtllib ${asset.id}.generated.mtl
o ${asset.id}
usemtl ${materialName}
v ${n(-x)} ${n(-y)} 0
v ${n(x)} ${n(-y)} 0
v ${n(x)} ${n(y)} 0
v ${n(-x)} ${n(y)} 0
v ${n(-x)} ${n(-y)} ${n(height)}
v ${n(x)} ${n(-y)} ${n(height)}
v ${n(x)} ${n(y)} ${n(height)}
v ${n(-x)} ${n(y)} ${n(height)}
f 1 4 3 2
f 5 6 7 8
f 1 2 6 5
f 2 3 7 6
f 3 4 8 7
f 4 1 5 8
`;
  const [red, green, blue] = asset.material.baseColor;
  const mtl = `${traces}
# Generated by crdd-ir. Do not edit.
newmtl ${materialName}
Ka 0 0 0
Kd ${n(red)} ${n(green)} ${n(blue)}
Ks 0 0 0
d 1
illum 1
`;

  return [
    generated(`${asset.id}.generated.obj`, obj),
    generated(`${asset.id}.generated.mtl`, mtl),
  ];
}

function generated(name: string, content: string): GeneratedFile {
  return {
    name,
    content,
    sha256: createHash("sha256").update(content).digest("hex"),
  };
}

function metersToCentimeters(value: number): number {
  return value * 100;
}

function n(value: number): string {
  return Number(value.toFixed(6)).toString();
}
