import type { CrddIr, FieldDefinition } from "./model.ts";
import type { TargetGeneratedFile } from "./target-registry.ts";

export function generateTypeScript(ir: CrddIr): TargetGeneratedFile[] {
  const operation = ir.operation;
  const name = identifier(operation.id);
  const inputType = objectType(operation.input);
  const stateType = objectType(operation.state);
  const outputType = operation.output ? tsType(operation.output) : "void";
  const eventType = operation.emits?.length
    ? operation.emits.map((event) => `{
  readonly type: ${JSON.stringify(event.type)};
  readonly payload: ${event.payload ? tsType(event.payload) : "void"};
}`).join(" | ")
    : "never";
  const inputSchema = JSON.stringify({ type: "object", properties: operation.input });
  const stateSchema = JSON.stringify({ type: "object", properties: operation.state });
  const outputSchema = operation.output ? JSON.stringify(operation.output) : "undefined";
  const kind = operation.kind;

  return [{
    name: `${name}.generated.ts`,
    content: `// Generated by CRDD IR. Do not edit.
// CRDD traces: ${operation.traces.join(", ")}

export type ${name}Input = ${inputType};
export type ${name}State = ${stateType};
export type ${name}Output = ${outputType};
export type ${name}Event = ${eventType};

export interface ${name}Context {
  readonly state: ${kind === "query" ? `Readonly<${name}State>` : name + "State"};
  readonly signal?: AbortSignal;
  readonly idempotencyKey?: string;
  emit(event: ${name}Event): void;
}

export interface ${name}Handler {
  execute(
    input: ${name}Input,
    context: ${name}Context,
  ): ${name}Output | Promise<${name}Output>;
}

export const ${name}Contract = ${JSON.stringify({
      operation: operation.id,
      kind,
      traces: operation.traces,
      execution: operation.execution ?? { mode: "sync" },
      events: operation.emits?.map((event) => ({
        type: event.type,
        delivery: event.delivery ?? "at-most-once",
        traces: event.traces,
      })) ?? [],
    }, null, 2)} as const;

const inputSchema: FieldSchema = ${inputSchema};
const stateSchema: FieldSchema = ${stateSchema};
const outputSchema: FieldSchema | undefined = ${outputSchema};

export function validate${name}Input(value: unknown): value is ${name}Input {
  return validateField(value, inputSchema);
}

export function validate${name}State(value: unknown): value is ${name}State {
  return validateField(value, stateSchema);
}

export function validate${name}Output(value: unknown): value is ${name}Output {
  return outputSchema === undefined ? value === undefined : validateField(value, outputSchema);
}

type FieldSchema = {
  type: string;
  nullable?: boolean;
  minimum?: number;
  maximum?: number;
  minLength?: number;
  maxLength?: number;
  pattern?: string;
  enum?: string[];
  minItems?: number;
  maxItems?: number;
  properties?: Record<string, FieldSchema>;
  items?: FieldSchema;
  values?: FieldSchema;
  discriminator?: string;
  variants?: FieldSchema[];
  optional?: boolean;
};

function validateField(value: unknown, schema: FieldSchema): boolean {
  if (value === null) return schema.nullable === true;
  switch (schema.type) {
    case "number":
      return typeof value === "number" && Number.isFinite(value) && numericRange(value, schema);
    case "integer":
      return typeof value === "number" && Number.isSafeInteger(value) && numericRange(value, schema);
    case "string":
      return typeof value === "string" &&
        (schema.enum === undefined || schema.enum.includes(value)) &&
        (schema.minLength === undefined || value.length >= schema.minLength) &&
        (schema.maxLength === undefined || value.length <= schema.maxLength) &&
        (schema.pattern === undefined || new RegExp(schema.pattern, "u").test(value));
    case "boolean":
      return typeof value === "boolean";
    case "array":
      return Array.isArray(value) &&
        (schema.minItems === undefined || value.length >= schema.minItems) &&
        (schema.maxItems === undefined || value.length <= schema.maxItems) &&
        value.every((entry) => validateField(entry, schema.items!));
    case "object":
      return isRecord(value) && validateProperties(value, schema.properties ?? {});
    case "map":
      return isRecord(value) &&
        Object.values(value).every((entry) => validateField(entry, schema.values!));
    case "union":
      return isRecord(value) && schema.variants?.filter((variant) => validateField(value, variant)).length === 1;
    default:
      return false;
  }
}

function validateProperties(
  value: Record<string, unknown>,
  properties: Record<string, FieldSchema>,
): boolean {
  if (Object.keys(value).some((key) => properties[key] === undefined)) return false;
  return Object.entries(properties).every(([key, field]) =>
    key in value ? validateField(value[key], field) : field.optional === true);
}

function numericRange(value: number, schema: FieldSchema): boolean {
  return (schema.minimum === undefined || value >= schema.minimum) &&
    (schema.maximum === undefined || value <= schema.maximum);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
`,
  }];
}

function objectType(properties: Record<string, FieldDefinition>): string {
  const fields = Object.entries(properties).map(([name, field]) =>
    `readonly ${propertyName(name)}${field.optional ? "?" : ""}: ${tsType(field)};`);
  return `{ ${fields.join(" ")} }`;
}

function tsType(field: FieldDefinition): string {
  let result: string;
  switch (field.type) {
    case "number":
    case "integer":
      result = "number";
      break;
    case "string":
      result = field.enum?.length ? field.enum.map((value) => JSON.stringify(value)).join(" | ") : "string";
      break;
    case "boolean":
      result = "boolean";
      break;
    case "object":
      result = objectType(field.properties);
      break;
    case "array":
      result = `Array<${tsType(field.items)}>`;
      break;
    case "map":
      result = `Record<string, ${tsType(field.values)}>`;
      break;
    case "union":
      result = field.variants.map(tsType).join(" | ");
      break;
  }
  return field.nullable ? `(${result}) | null` : result;
}

function identifier(value: string): string {
  const result = value.replace(/[^A-Za-z0-9_]/g, "_");
  return /^[A-Za-z_]/.test(result) ? result : `_${result}`;
}

function propertyName(value: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value) ? value : JSON.stringify(value);
}
