import { createHash } from "node:crypto";
import type { CrddIr, Effect, FieldDefinition, Operation, PortableRule } from "./model.ts";
import type { UnityTargetProfile } from "./unity-target.ts";
import { generateTestManifest } from "./test-manifest.ts";
import { simulate } from "./simulator.ts";
import { snapshotOwnershipMarker } from "./snapshot-ownership.ts";
import { parseSourceExpression, type ExpressionNode } from "./source-expression.ts";

export type GeneratedUnityFile = {
  name: string;
  content: string;
  sha256: string;
};

export function generateUnity(
  ir: CrddIr,
  profile: UnityTargetProfile,
  metadata: { irSha256?: string; generatorVersion?: string } = {},
): GeneratedUnityFile[] {
  const operation = projectNumericTypes(ir.operation, profile);
  const name = identifier(operation.id);
  const files = [
    { name: `${name}.Generated.cs`, content: contract(operation, profile, metadata) },
    { name: `${name}.Bridge.Generated.cs`, content: bridge(operation, profile) },
    { name: `${name}.Bridge.Generated.Tests.cs`, content: bridgeTests(operation, profile) },
    {
      name: `${name}.Conformance.Generated.Tests.cs`,
      content: conformanceTests(ir, operation, profile),
    },
  ];
  return files.map((file) => ({
    ...file,
    sha256: createHash("sha256").update(file.content).digest("hex"),
  }));
}

function conformanceTests(
  ir: CrddIr,
  operation: Operation,
  profile: UnityTargetProfile,
): string {
  const name = identifier(operation.id);
  const cases = generateTestManifest(ir).cases.map((testCase, index) => {
    const expected = simulate(ir, testCase.arrange);
    const assertions = [
      `            Assert.That(result.Succeeded, Is.${expected.ok ? "True" : "False"});`,
      ...(!expected.ok
        ? [`            Assert.That(${name}Operation.ErrorCode(result.Error), Is.EqualTo("${escape(expected.error)}"));`]
        : []),
      ...stateAssertions(
        expected.state,
        operation.state,
        "result.State",
        `case ${index + 1}`,
      ),
      ...csSemanticAssertions(expected, operation),
    ].join("\n");
    return `        [Test]
        public void ${identifier(testCase.id)}()
        {
            var input = ${objectLiteral(testCase.arrange.input, operation.input, `${name}Input`, name, "Input")};
            var state = ${objectLiteral(testCase.arrange.state, operation.state, `${name}State`, name, "State")};
            var result = ${name}Operation.Execute(input, state);
${assertions}
        }`;
  }).join("\n\n");
  const snapshotOwnership = csSnapshotOwnershipTests(ir, operation);
  return `// Generated by crdd-ir. Do not edit.
#if UNITY_INCLUDE_TESTS
using System.Collections.Generic;
using NUnit.Framework;

namespace ${profile.namespace}.Tests
{
    public sealed class ${name}ConformanceGeneratedTests
    {
${cases}
${snapshotOwnership ? `\n\n${snapshotOwnership}` : ""}
    }
}
#endif
`;
}

function csSnapshotOwnershipTests(ir: CrddIr, operation: Operation): string {
  const inputEntry = Object.entries(operation.input).find(([, field]) =>
    field.type === "array" && field.items.type === "object" &&
    Object.values(field.items.properties).some((child) =>
      child.type === "array" && child.items.type !== "object"
    )
  );
  if (!inputEntry) return "";
  const [inputName, inputField] = inputEntry;
  if (inputField.type !== "array" || inputField.items.type !== "object") return "";
  const nestedEntry = Object.entries(inputField.items.properties).find(([, child]) =>
    child.type === "array" && child.items.type !== "object"
  );
  if (!nestedEntry) return "";
  const [nestedName, nestedField] = nestedEntry;
  if (nestedField.type !== "array") return "";
  const effect = operation.effects.find((candidate) =>
    candidate.action === "assign" && candidate.expression === `input.${inputName}` &&
    /^state\.[A-Za-z_]\w*$/.test(candidate.target)
  );
  if (!effect || effect.action !== "assign") return "";
  const assignedStateName = effect.target.slice("state.".length);
  const assignedStateField = operation.state[assignedStateName];
  if (assignedStateField?.type !== "array" || assignedStateField.items.type !== "object") return "";
  const clonedStateEntry = Object.entries(operation.state).find(([, field]) =>
    field.type === "array" && field.items.type === "object" &&
    Object.values(field.items.properties).some((child) => child.type === "array")
  );
  if (!clonedStateEntry) return "";
  const [clonedStateName, clonedStateField] = clonedStateEntry;
  if (clonedStateField.type !== "array" || clonedStateField.items.type !== "object") return "";
  const clonedNestedEntry = Object.entries(clonedStateField.items.properties).find(([, child]) =>
    child.type === "array" && child.items.type !== "object"
  );
  if (!clonedNestedEntry) return "";
  const [clonedNestedName, clonedNestedField] = clonedNestedEntry;
  if (clonedNestedField.type !== "array") return "";

  const successCase = generateTestManifest(ir).cases.find((item) => item.expect.ok);
  if (!successCase) return "";
  const success = structuredClone(successCase.arrange);
  const uniqueRule = (operation.portableRules ?? []).find((rule) =>
    rule.kind === "collection.unique" && rule.collection === `input.${inputName}` && rule.key
  );
  const key = uniqueRule?.kind === "collection.unique" ? uniqueRule.key : undefined;
  const first = ownershipObjectValue(inputField.items, key, "ownership-a", false);
  const second = ownershipObjectValue(inputField.items, key, "ownership-b", true);
  success.input[inputName] = [first, second];
  success.state[clonedStateName] = [ownershipObjectValue(clonedStateField.items, key, "initial", false)];
  success.state[assignedStateName] = [ownershipObjectValue(assignedStateField.items, key, "previous", false)];
  refreshEvidenceHash(success.input, operation);

  const failure = structuredClone(success);
  if (key) {
    const duplicate = structuredClone(first) as Record<string, unknown>;
    duplicate[key] = (first as Record<string, unknown>)[key];
    failure.input[inputName] = [first, duplicate];
    refreshEvidenceHash(failure.input, operation);
  } else {
    failure.input = structuredClone(success.input);
    const hashRule = (operation.portableRules ?? []).find((rule) => rule.kind === "evidence.canonical-hash");
    if (hashRule?.kind === "evidence.canonical-hash") {
      failure.input[hashRule.hash.slice("input.".length)] = "0".repeat(64);
    }
  }

  const operationName = identifier(operation.id);
  const successInput = objectLiteral(success.input, operation.input, `${operationName}Input`, operationName, "Input");
  const successState = objectLiteral(success.state, operation.state, `${operationName}State`, operationName, "State");
  const failureInput = objectLiteral(failure.input, operation.input, `${operationName}Input`, operationName, "Input");
  const failureState = objectLiteral(failure.state, operation.state, `${operationName}State`, operationName, "State");
  const inputCollection = `input.${csField(inputName, inputField)}`;
  const assignedCollection = `result.State.${csField(assignedStateName, assignedStateField)}`;
  const initialCollection = `state.${csField(clonedStateName, clonedStateField)}`;
  const clonedCollection = `result.State.${csField(clonedStateName, clonedStateField)}`;
  const inputNested = `${inputCollection}[0].${csField(nestedName, nestedField)}`;
  const assignedNested = `${assignedCollection}[0].${csField(nestedName, nestedField)}`;
  const initialNested = `${initialCollection}[0].${csField(clonedNestedName, clonedNestedField)}`;
  const clonedNested = `${clonedCollection}[0].${csField(clonedNestedName, clonedNestedField)}`;
  const mutation = typedLiteral(
    sampleOwnershipScalar(nestedField.items, "mutated"),
    nestedField.items,
    operationName,
    "",
    "Value",
  );

  return `        // CRDD-SNAPSHOT-OWNERSHIP: ${snapshotOwnershipMarker()}
        [Test]
        public void SnapshotOwnershipIsDeepOnSuccess()
        {
            var input = ${successInput};
            var state = ${successState};
            var result = ${operationName}Operation.Execute(input, state);
            Assert.That(result.Succeeded, Is.True);
            Assert.That(ReferenceEquals(${inputCollection}, ${assignedCollection}), Is.False);
            Assert.That(ReferenceEquals(${inputNested}, ${assignedNested}), Is.False);
            Assert.That(${assignedNested}, Is.EqualTo(new[] { ${((first as Record<string, unknown>)[nestedName] as unknown[]).map((item) => typedLiteral(item, nestedField.items, operationName, "", "Value")).join(", ")} }));
            Assert.That(${assignedCollection}[1].${csField(nestedName, nestedField)}, Is.Empty);
            var assignedCount = ${assignedNested}.Count;
            ${inputNested}.Add(${mutation});
            Assert.That(${assignedNested}.Count, Is.EqualTo(assignedCount));
            Assert.That(ReferenceEquals(${initialNested}, ${clonedNested}), Is.False);
            var clonedCount = ${clonedNested}.Count;
            ${initialNested}.Add(${mutation});
            Assert.That(${clonedNested}.Count, Is.EqualTo(clonedCount));
            var initialCount = ${initialNested}.Count;
            ${clonedNested}.Add(${mutation});
            Assert.That(${initialNested}.Count, Is.EqualTo(initialCount));
        }

        [Test]
        public void SnapshotOwnershipIsDeepOnRollback()
        {
            var input = ${failureInput};
            var state = ${failureState};
            var result = ${operationName}Operation.Execute(input, state);
            Assert.That(result.Succeeded, Is.False);
            Assert.That(ReferenceEquals(${initialNested}, ${clonedNested}), Is.False);
            var clonedCount = ${clonedNested}.Count;
            ${initialNested}.Add(${mutation});
            Assert.That(${clonedNested}.Count, Is.EqualTo(clonedCount));
            var initialCount = ${initialNested}.Count;
            ${clonedNested}.Add(${mutation});
            Assert.That(${initialNested}.Count, Is.EqualTo(initialCount));
        }`;
}

function ownershipObjectValue(
  field: Extract<FieldDefinition, { type: "object" }>,
  key: string | undefined,
  keyValue: string,
  emptyNested: boolean,
): Record<string, unknown> {
  return Object.fromEntries(Object.entries(field.properties).map(([name, child]) => {
    if (name === key) return [name, keyValue];
    if (child.type === "array" && child.items.type !== "object") {
      return [name, emptyNested ? [] : [
        sampleOwnershipScalar(child.items, "first"),
        sampleOwnershipScalar(child.items, "second"),
      ]];
    }
    return [name, sampleOwnershipScalar(child, keyValue)];
  }));
}

function sampleOwnershipScalar(field: FieldDefinition, text: string): unknown {
  if (field.type === "string") return field.enum?.[0] ?? text;
  if (field.type === "integer" || field.type === "number") return field.minimum ?? 1;
  if (field.type === "boolean") return true;
  if (field.type === "array") return [];
  if (field.type === "object") return ownershipObjectValue(field, undefined, text, false);
  if (field.type === "opaque") return { base64: "", sha256: createHash("sha256").update("").digest("hex"), active: false };
  return {};
}

function refreshEvidenceHash(input: Record<string, unknown>, operation: Operation): void {
  const rule = (operation.portableRules ?? []).find((candidate) =>
    candidate.kind === "evidence.canonical-hash" && candidate.source === "input"
  );
  if (rule?.kind !== "evidence.canonical-hash") return;
  const hashName = rule.hash.slice("input.".length);
  const payload = structuredClone(input);
  delete payload[hashName];
  input[hashName] = createHash("sha256").update(canonicalJson(payload)).digest("hex");
}

function contract(
  operation: Operation,
  profile: UnityTargetProfile,
  metadata: { irSha256?: string; generatorVersion?: string },
): string {
  const name = identifier(operation.id);
  const collectionClasses = new Map<string, Extract<FieldDefinition, { type: "object" }>>();
  for (const [fieldName, field] of [...Object.entries(operation.input), ...Object.entries(operation.state)]) {
    const item = field.type === "array" ? field.items : field.type === "map" ? field.values : undefined;
    if (item?.type === "object") collectionClasses.set(csCollectionItemType(field, name, fieldName), item);
  }
  const nested = [
    ...(hasOpaque(operation) ? [`public sealed class CrddOpaqueValue
{
    public string Base64 = "";
    public string Sha256 = "";
    public bool Active;
}`] : []),
    ...Object.entries(operation.input).flatMap(([fieldName, field]) =>
      field.type === "object" ? [objectClass(name, "Input", fieldName, field)] : []
    ),
    ...Object.entries(operation.state).flatMap(([fieldName, field]) =>
      field.type === "object" ? [objectClass(name, "State", fieldName, field)] : []
    ),
    ...Object.entries(operation.input).flatMap(([fieldName, field]) =>
      field.type === "union" ? [unionClasses(name, "Input", fieldName, field)] : []
    ),
    ...Object.entries(operation.state).flatMap(([fieldName, field]) =>
      field.type === "union" ? [unionClasses(name, "State", fieldName, field)] : []
    ),
    ...[...collectionClasses.entries()].map(([typeName, item]) => objectClassNamed(typeName, item, name)),
    ...(operation.output?.type === "object" && operation.returns !== undefined
      ? [objectClass(name, "", "Output", operation.output)] : []),
    ...(operation.emits ?? []).flatMap((event) =>
      event.value !== undefined && event.payload?.type === "object"
        ? [objectClass(name, "", `${identifier(event.type)}Payload`, event.payload)] : []),
    ...((operation.emits ?? []).some((event) => event.value !== undefined) ? [`public sealed class ${name}Event
{
    public string Type = "";
${(operation.emits ?? []).filter((event) => event.value !== undefined)
  .map((event) => `    public ${name}${identifier(event.type)}Payload ${identifier(event.type)} = new();`).join("\n")}
}`] : []),
  ].join("\n\n");
  const inputFields = Object.entries(operation.input)
    .map(([fieldName, field]) =>
      `        public ${csType(field, name, "Input", fieldName)} ${csField(fieldName, field)} = ${csDefault(field)};`
    ).join("\n");
  const stateFields = Object.entries(operation.state)
    .map(([fieldName, field]) =>
      `        public ${csType(field, name, "State", fieldName)} ${csField(fieldName, field)} = ${csDefault(field)};`
    ).join("\n");
  const errors = operation.errors.map((error) => `        ${identifier(error.code)},`).join("\n");
  const checks = operation.requires.map((requirement) => {
    const error = operation.errors.find((item) => item.code === requirement.error)!;
    return `            try
            {
                if (${requirement.when ? `checked(${csExpression(requirement.when, operation)}) && ` : ""}!(checked(${csExpression(requirement.expression, operation)})))
                    return Failure(${name}Error.${identifier(requirement.error)}, "${escape(requirement.id)}", initialState, new[] { ${error.traces.map((trace) => `"${escape(trace)}"`).join(", ")} });
            }
            catch (OverflowException)
            {
                return Failure(${name}Error.${identifier(requirement.error)}, "${escape(requirement.id)}", initialState, new[] { ${error.traces.map((trace) => `"${escape(trace)}"`).join(", ")} });
            }`;
  }).join("\n\n");
  const portableChecks = (operation.portableRules ?? [])
    .map((rule) => csPortableRule(rule, operation))
    .join("\n\n");
  const effects = operation.effects.map((effect) => csEffect(effect, operation)).join("\n");
  const semanticResult = csSemanticResult(operation);
  const errorCases = operation.errors
    .map((error) => `                ${name}Error.${identifier(error.code)} => "${escape(error.code)}",`)
    .join("\n");
  const opaqueHelpers = hasOpaque(operation) ? `
        private static bool OpaqueValid(CrddOpaqueValue value)
        {
            try
            {
                var bytes = Convert.FromBase64String(value.Base64);
                if (Convert.ToBase64String(bytes) != value.Base64) return false;
                using var sha = SHA256.Create();
                var digest = BitConverter.ToString(sha.ComputeHash(bytes)).Replace("-", "").ToLowerInvariant();
                return digest == value.Sha256;
            }
            catch (FormatException)
            {
                return false;
            }
        }

        private static CrddOpaqueValue CloneOpaque(CrddOpaqueValue value) => new()
        {
            Base64 = value.Base64,
            Sha256 = value.Sha256,
            Active = value.Active
        };
` : "";
  const unionHelpers = csUnionCloneHelpers(operation);
  const evidenceHelpers = csEvidenceHelpers(operation);
  const traceHeader = operation.traces.map((trace) => `// CRDD-TRACE: ${trace}`).join("\n");
  return `// Generated by crdd-ir. Do not edit.
${metadata.irSha256 ? `// CRDD-IR Generator: ${metadata.generatorVersion ?? "unknown"}\n// CRDD-IR Input SHA-256: ${metadata.irSha256}\n` : ""}${traceHeader}
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
${hasOpaque(operation) || hasEvidenceHash(operation) ? "using System.Security.Cryptography;\nusing System.Text;" : ""}

namespace ${profile.namespace}
{
${indent(nested, 4)}

    public sealed class ${name}Input
    {
${inputFields}
    }

    public sealed class ${name}State
    {
${stateFields}
    }

    public enum ${name}Error
    {
        None,
${errors}
    }

    public sealed class ${name}Result
    {
        public bool Succeeded;
        public ${name}Error Error;
        public string FailedRequirement = "";
        public ${name}State State = new();
${operation.returns === undefined ? "" : `        public ${name}Output Output = new();\n`}${(operation.emits ?? []).some((event) => event.value !== undefined) ? `        public IReadOnlyList<${name}Event> Events = Array.Empty<${name}Event>();\n` : ""}        public IReadOnlyList<string> Traces = Array.Empty<string>();
    }

    public static class ${name}Operation
    {
        public static ${name}Result Execute(${name}Input input, ${name}State initialState)
        {
${checks}
${checks && portableChecks ? "\n" : ""}${portableChecks}

            var result = new ${name}Result
            {
                Succeeded = true,
                State = CloneState(initialState),
                Traces = new[] { ${operation.traces.map((trace) => `"${escape(trace)}"`).join(", ")} }
            };
${effects}
${semanticResult}
            return result;
        }

        public static string ErrorCode(${name}Error error) => error switch
        {
${errorCases}
                _ => ""
        };

        private static ${name}Result Failure(
            ${name}Error error,
            string failedRequirement,
            ${name}State initialState,
            IReadOnlyList<string> traces) => new()
        {
            Error = error,
            FailedRequirement = failedRequirement,
            State = CloneState(initialState),
            Traces = traces
        };

        private static ${name}State CloneState(${name}State source) => new()
        {
${stateCloneAssignments(operation)}
        };
${opaqueHelpers}
${unionHelpers}
${evidenceHelpers}
    }
}
`;
}

function csUnionCloneHelpers(operation: Operation): string {
  const operationName = identifier(operation.id);
  return Object.entries(operation.state)
    .filter((entry): entry is [string, Extract<FieldDefinition, { type: "union" }>] =>
      entry[1].type === "union"
    )
    .map(([name, field]) => {
      const typeName = `${operationName}State${identifier(name)}Union`;
      const copies = field.variants.map((variant) => {
        const variantName = identifier(unionVariant(field, variant));
        const assignments = Object.entries(variant.properties)
          .filter(([property]) => property !== field.discriminator)
          .map(([property, child]) => {
            const member = csField(property, child);
            return `${member} = source.${variantName}.${member}`;
          }).join(", ");
        return `            ${typeName}Variant.${variantName} => new ${typeName}
            {
                Variant = ${typeName}Variant.${variantName},
                ${variantName} = new ${typeName}${variantName}Payload { ${assignments} }
            },`;
      }).join("\n");
      return `
        private static ${typeName} Clone${identifier(name)}Union(${typeName} source) =>
            source.Variant switch
            {
${copies}
                _ => new ${typeName} { Variant = ${typeName}Variant.Unknown }
            };
`;
    }).join("\n");
}

function csPortableRule(rule: PortableRule, operation: Operation): string {
  const name = identifier(operation.id);
  const error = operation.errors.find((entry) => entry.code === rule.error);
  if (!error) throw new Error(`Portable rule "${rule.id}" uses unknown error "${rule.error}"`);
  const failure = `return Failure(${name}Error.${identifier(rule.error)}, "${escape(rule.id)}", initialState, new[] { ${error.traces.map((trace) => `"${escape(trace)}"`).join(", ")} });`;
  const marker = portableSemanticsMarker(rule);
  if (rule.kind === "evidence.canonical-hash") {
    const hash = csPortablePath(rule.hash, operation);
    const source = rule.source === "input" ? "input" : "initialState";
    return `            // ${rule.id}: ${rule.kind}
            // CRDD-PORTABLE-SEMANTICS: ${marker}
            if (Canonical${rule.source === "input" ? "Input" : "State"}Sha256(${source}) != ${hash})
                ${failure}`;
  }
  if (rule.kind === "opaque.integrity") {
    return `            // ${rule.id}: ${rule.kind}
            // CRDD-PORTABLE-SEMANTICS: ${marker}
            if (!OpaqueValid(${csPortablePath(rule.target, operation)}))
                ${failure}`;
  }
  if (rule.kind === "opaque.immutable-when-inactive") {
    const current = csPortablePath(rule.current, operation);
    const proposed = csPortablePath(rule.proposed, operation);
    return `            // ${rule.id}: ${rule.kind}
            // CRDD-PORTABLE-SEMANTICS: ${marker}
            if (!OpaqueValid(${current}) || !OpaqueValid(${proposed}) ||
                (!${current}.Active &&
                (${current}.Base64 != ${proposed}.Base64 ||
                 ${current}.Sha256 != ${proposed}.Sha256 ||
                 ${current}.Active != ${proposed}.Active)))
                ${failure}`;
  }
  if (rule.kind === "opaque.reject-edit-when-inactive") {
    const current = csPortablePath(rule.current, operation);
    const intent = csPortablePath(rule.intent, operation);
    return `            // ${rule.id}: ${rule.kind}
            // CRDD-PORTABLE-SEMANTICS: ${marker}
            if (!OpaqueValid(${current}) || (!${current}.Active && ${intent}))
                ${failure}`;
  }
  if (rule.kind === "collection.not-contains") {
    const collection = csCollectionValues(rule.collection, operation);
    const item = csCollectionItem(operation, rule.collection);
    const targetKey = csField(rule.targetKey, item.properties[rule.targetKey]);
    const value = csPortablePath(rule.value, operation);
    return `            // ${rule.id}: ${rule.kind}
            // CRDD-PORTABLE-SEMANTICS: ${marker}
            foreach (var item in ${collection})
                if (item.${targetKey} == ${value})
                    ${failure}`;
  }
  if (rule.kind === "collection.prospective-unique") {
    const candidates = csCollectionValues(rule.candidates, operation);
    const existing = csCollectionValues(rule.existing, operation);
    const candidateItem = csCollectionItem(operation, rule.candidates);
    const existingItem = csCollectionItem(operation, rule.existing);
    const candidateKey = csField(rule.candidateKey, candidateItem.properties[rule.candidateKey]);
    const existingKey = csField(rule.existingKey, existingItem.properties[rule.existingKey]);
    return `            // ${rule.id}: ${rule.kind}
            // CRDD-PORTABLE-SEMANTICS: ${marker}
            {
                var proposed = new HashSet<string>();
                foreach (var candidate in ${candidates})
                {
                    var key = Convert.ToString(candidate.${candidateKey})!;
                    if (string.IsNullOrEmpty(key) || !proposed.Add(key))
                        ${failure}
                    foreach (var current in ${existing})
                        if (current.${existingKey} == candidate.${candidateKey})
                            ${failure}
                }
            }`;
  }
  const collection = csCollectionValues(rule.collection, operation);
  if (rule.kind === "collection.unique") {
    const collectionField = portableCollectionField(operation, rule.collection);
    const itemField = collectionField.type === "array" ? collectionField.items : collectionField.values;
    const keyExpression = itemField.type === "object"
      ? `item.${csField(rule.key!, itemField.properties[rule.key!])}`
      : "item";
    return `            // ${rule.id}: ${rule.kind}
            // CRDD-PORTABLE-SEMANTICS: ${marker}
            {
                var seen = new HashSet<string>();
                foreach (var item in ${collection})
                    if (string.IsNullOrEmpty(Convert.ToString(${keyExpression})) || !seen.Add(Convert.ToString(${keyExpression})!))
                        ${failure}
            }`;
  }
  const item = csCollectionItem(operation, rule.collection);
  if (rule.kind === "collection.reference") {
    return csReferenceRule(rule, collection, item, rule.reference, rule.target, rule.targetKey,
      rule.targetType, failure, operation);
  }
  if (rule.kind === "collection.membership") {
    return csReferenceRule(rule, collection, item, rule.parentReference, rule.parents, rule.parentKey,
      undefined, failure, operation);
  }
  const elements = csCollectionValues(rule.elements, operation);
  const elementItem = csCollectionItem(operation, rule.elements);
  const from = csField(rule.from, item.properties[rule.from]);
  const to = csField(rule.to, item.properties[rule.to]);
  const key = csField(rule.elementKey, elementItem.properties[rule.elementKey]);
  const fromType = csTypePredicate("element", elementItem, rule.fromType);
  const toType = csTypePredicate("element", elementItem, rule.toType);
  return `            // ${rule.id}: ${rule.kind}
            // CRDD-PORTABLE-SEMANTICS: ${marker}
            foreach (var relation in ${collection})
            {
                var fromFound = false;
                var toFound = false;
                foreach (var element in ${elements})
                {
                    fromFound = fromFound || (element.${key} == relation.${from}${fromType});
                    toFound = toFound || (element.${key} == relation.${to}${toType});
                }
                if (!fromFound || !toFound)
                    ${failure}
            }`;
}

function csReferenceRule(
  rule: PortableRule,
  collection: string,
  item: Extract<FieldDefinition, { type: "object" }>,
  reference: string,
  targetPath: string,
  targetKey: string,
  type: { field: string; equals: string } | undefined,
  failure: string,
  operation: Operation,
): string {
  const target = csCollectionValues(targetPath, operation);
  const targetItem = csCollectionItem(operation, targetPath);
  const ref = csField(reference, item.properties[reference]);
  const key = csField(targetKey, targetItem.properties[targetKey]);
  const predicate = csTypePredicate("candidate", targetItem, type);
  return `            // ${rule.id}: ${rule.kind}
            // CRDD-PORTABLE-SEMANTICS: ${portableSemanticsMarker(rule)}
            foreach (var item in ${collection})
            {
                var found = false;
                foreach (var candidate in ${target})
                    found = found || (candidate.${key} == item.${ref}${predicate});
                if (!found)
                    ${failure}
            }`;
}

function portableSemanticsMarker(rule: PortableRule): string {
  return Buffer.from(canonicalJson(rule), "utf8").toString("base64");
}

function canonicalJson(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`;
  if (value && typeof value === "object") {
    return `{${Object.keys(value as Record<string, unknown>).sort()
      .map((key) => `${JSON.stringify(key)}:${canonicalJson((value as Record<string, unknown>)[key])}`)
      .join(",")}}`;
  }
  return JSON.stringify(value);
}

function csTypePredicate(
  variable: string,
  item: Extract<FieldDefinition, { type: "object" }>,
  type?: { field: string; equals: string },
): string {
  return type
    ? ` && ${variable}.${csField(type.field, item.properties[type.field])} == "${escape(type.equals)}"`
    : "";
}

function csPortablePath(path: string, operation: Operation): string {
  const [scope, name, ...rest] = path.split(".");
  const field = (scope === "input" ? operation.input : operation.state)[name];
  if (!field || rest.length) throw new Error(`Portable Unity path must be top-level: "${path}"`);
  return `${scope === "input" ? "input" : "initialState"}.${csField(name, field)}`;
}

function csCollectionItem(
  operation: Operation,
  path: string,
): Extract<FieldDefinition, { type: "object" }> {
  const [scope, name] = path.split(".");
  const field = (scope === "input" ? operation.input : operation.state)[name];
  const item = field?.type === "array" ? field.items : field?.type === "map" ? field.values : undefined;
  if (item?.type !== "object") {
    throw new Error(`Portable collection "${path}" must be an array or map of objects`);
  }
  return item;
}

function csCollectionValues(path: string, operation: Operation): string {
  const raw = csPortablePath(path, operation);
  const [scope, name] = path.split(".");
  const field = (scope === "input" ? operation.input : operation.state)[name];
  return field?.type === "map" ? `${raw}.Values` : raw;
}

function hasEvidenceHash(operation: Operation): boolean {
  return (operation.portableRules ?? []).some((rule) => rule.kind === "evidence.canonical-hash");
}

function csEvidenceHelpers(operation: Operation): string {
  if (!hasEvidenceHash(operation)) return "";
  const name = identifier(operation.id);
  const sources = (["input", "state"] as const).map((source) => {
    const fields = source === "input" ? operation.input : operation.state;
    const type = `${name}${source === "input" ? "Input" : "State"}`;
    const value = source === "input" ? "input" : "state";
    const hashFields = new Set((operation.portableRules ?? [])
      .filter((rule) => rule.kind === "evidence.canonical-hash" && rule.source === source)
      .map((rule) => rule.hash.split(".").slice(1).join(".")));
    const entries = Object.entries(fields).filter(([field]) => !hashFields.has(field)).sort(([a], [b]) => a.localeCompare(b))
      .map(([field, definition]) =>
        `JsonString("${field}") + ":" + ${csCanonicalValue(definition, `${value}.${csField(field, definition)}`, name, source, field)}`
      );
    return `        public static string Canonical${source === "input" ? "Input" : "State"}Json(${type} ${value}) =>
            "{" + ${entries.join(' + "," + ')} + "}";

        public static string Canonical${source === "input" ? "Input" : "State"}Sha256(${type} ${value})
        {
            using var sha = SHA256.Create();
            var bytes = sha.ComputeHash(Encoding.UTF8.GetBytes(Canonical${source === "input" ? "Input" : "State"}Json(${value})));
            return BitConverter.ToString(bytes).Replace("-", "").ToLowerInvariant();
        }`;
  }).join("\n\n");
  return `
        private static string JsonString(string value)
        {
            var escaped = new StringBuilder(value.Length + 2);
            escaped.Append('"');
            for (var index = 0; index < value.Length; index++)
            {
                var character = value[index];
                switch (character)
                {
                    case '"': escaped.Append('\\\\').Append('"'); break;
                    case '\\\\': escaped.Append("\\\\\\\\"); break;
                    case '\\b': escaped.Append("\\\\b"); break;
                    case '\\f': escaped.Append("\\\\f"); break;
                    case '\\n': escaped.Append("\\\\n"); break;
                    case '\\r': escaped.Append("\\\\r"); break;
                    case '\\t': escaped.Append("\\\\t"); break;
                    default:
                        if (character <= 0x1f) escaped.Append("\\\\u").Append(((int)character).ToString("x4"));
                        else if (char.IsHighSurrogate(character) && index + 1 < value.Length &&
                            char.IsLowSurrogate(value[index + 1]))
                        {
                            escaped.Append(character).Append(value[++index]);
                        }
                        else if (char.IsSurrogate(character))
                            escaped.Append("\\\\u").Append(((int)character).ToString("x4"));
                        else escaped.Append(character);
                        break;
                }
            }
            return escaped.Append('"').ToString();
        }

        private static string CanonicalArray<T>(IEnumerable<T> values, Func<T, string> serialize) =>
            "[" + string.Join(",", values.Select(serialize)) + "]";

${sources}
`;
}

function csCanonicalValue(
  field: FieldDefinition,
  access: string,
  operation: string,
  scope: string,
  fieldName: string,
): string {
  if (field.type === "string") return `JsonString(${access})`;
  if (field.type === "boolean") return `(${access} ? "true" : "false")`;
  if (field.type === "integer") return `${access}.ToString(CultureInfo.InvariantCulture)`;
  if (field.type === "number") {
    throw new Error("Canonical Evidence cannot contain binary floating-point fields; use a decimal string");
  }
  if (field.type === "array") {
    return `CanonicalArray(${access}, item => ${csCanonicalValue(field.items, "item", operation, scope, `${fieldName}Item`)})`;
  }
  if (field.type === "object") {
    const entries = Object.entries(field.properties).sort(([a], [b]) => a.localeCompare(b))
      .map(([name, child]) =>
        `JsonString("${name}") + ":" + ${csCanonicalValue(child, `${access}.${csField(name, child)}`, operation, scope, name)}`
      );
    return `"{" + ${entries.join(' + "," + ')} + "}"`;
  }
  if (field.type === "union") {
    const typeName = `${operation}${identifier(scope)}${identifier(fieldName)}Union`;
    const variants = field.variants.map((variant) => {
      const variantName = identifier(unionVariant(field, variant));
      const entries = Object.entries(variant.properties).sort(([a], [b]) => a.localeCompare(b)).map(([name, child]) =>
        name === field.discriminator
          ? `JsonString("${name}") + ":" + JsonString("${unionVariant(field, variant)}")`
          : `JsonString("${name}") + ":" + ${csCanonicalValue(child, `${access}.${variantName}.${csField(name, child)}`, operation, scope, `${fieldName}${variantName}${name}`)}`
      );
      return `${access}.Variant == ${typeName}Variant.${variantName} ? "{" + ${entries.join(' + "," + ')} + "}" : `;
    }).join("");
    return `(${variants}"null")`;
  }
  return `"null"`;
}

function portableCollectionField(
  operation: Operation,
  path: string,
): Extract<FieldDefinition, { type: "array" | "map" }> {
  const [scope, name, ...rest] = path.split(".");
  const field = (scope === "input" ? operation.input : operation.state)[name];
  if (rest.length || (field?.type !== "array" && field?.type !== "map")) {
    throw new Error(`Portable collection path must be a top-level array or map: "${path}"`);
  }
  return field;
}

function hasOpaque(operation: Operation): boolean {
  const visit = (field: FieldDefinition): boolean =>
    field.type === "opaque" ||
    (field.type === "object" && Object.values(field.properties).some(visit)) ||
    (field.type === "array" && visit(field.items)) ||
    (field.type === "map" && visit(field.values)) ||
    (field.type === "union" && field.variants.some(visit));
  return [...Object.values(operation.input), ...Object.values(operation.state)].some(visit);
}

function bridge(operation: Operation, profile: UnityTargetProfile): string {
  const name = identifier(operation.id);
  return `// Generated by crdd-ir. Do not edit.
#nullable enable
using System;
using System.Collections.Generic;

namespace ${profile.namespace}
{
    public enum ${name}BridgeFailure
    {
        None, RequestMapping, SnapshotLoad, Contract, RevisionOverflow, Commit
    }

    public sealed class ${name}BridgeRequestDto
    {
        public ${name}Input Input = new();
    }

    public sealed class ${name}BridgeSnapshotDto
    {
        public ${name}State State = new();
        public ulong Revision;
    }

    public sealed class ${name}BridgeErrorDto
    {
        public ${name}BridgeFailure Failure;
        public string Code = "";
        public string Diagnostic = "";
        public string FailedRequirement = "";
        public IReadOnlyList<string> Traces = Array.Empty<string>();
    }

    public sealed class ${name}BridgeResultDto
    {
        public bool Succeeded;
        public ${name}BridgeSnapshotDto Snapshot = new();
${operation.returns === undefined ? "" : `        public ${name}Output Output = new();\n`}${(operation.emits ?? []).some((event) => event.value !== undefined) ? `        public IReadOnlyList<${name}Event> Events = Array.Empty<${name}Event>();\n` : ""}        public ${name}BridgeErrorDto Error = new();
    }

    public interface I${name}ProductAdapter
    {
        bool TryBuildRequest(out ${name}BridgeRequestDto request, out string diagnostic);
        bool TryLoadSnapshot(out ${name}BridgeSnapshotDto snapshot, out string diagnostic);
        bool TryCommitSnapshot(
            ${name}BridgeSnapshotDto candidate,
            ulong expectedRevision,
            out string diagnostic);
    }

    public static class ${name}Bridge
    {
        public static ${name}BridgeResultDto Execute(I${name}ProductAdapter adapter)
        {
            if (!adapter.TryBuildRequest(out var request, out var diagnostic))
                return Failure(${name}BridgeFailure.RequestMapping, "BRIDGE_REQUEST_MAPPING", diagnostic, new());

            if (!adapter.TryLoadSnapshot(out var original, out diagnostic))
                return Failure(${name}BridgeFailure.SnapshotLoad, "BRIDGE_SNAPSHOT_LOAD", diagnostic, original ?? new());

            var contract = ${name}Operation.Execute(request.Input, original.State);
            if (!contract.Succeeded)
            {
                var failure = Failure(${name}BridgeFailure.Contract, ${name}Operation.ErrorCode(contract.Error), "", original);
                failure.Error.FailedRequirement = contract.FailedRequirement;
                failure.Error.Traces = contract.Traces;
                return failure;
            }
            if (original.Revision == ulong.MaxValue)
                return Failure(${name}BridgeFailure.RevisionOverflow, "BRIDGE_REVISION_OVERFLOW", "Snapshot revision cannot be incremented.", original);

            var candidate = new ${name}BridgeSnapshotDto
            {
                State = contract.State,
                Revision = original.Revision + 1
            };
            if (!adapter.TryCommitSnapshot(candidate, original.Revision, out diagnostic))
                return Failure(${name}BridgeFailure.Commit, "BRIDGE_COMMIT", diagnostic, original);

            return new ${name}BridgeResultDto
            {
                Succeeded = true,
                Snapshot = candidate${operation.returns === undefined ? "" : ",\n                Output = contract.Output"}${(operation.emits ?? []).some((event) => event.value !== undefined) ? ",\n                Events = contract.Events" : ""}
            };
        }

        private static ${name}BridgeResultDto Failure(
            ${name}BridgeFailure failure, string code, string diagnostic, ${name}BridgeSnapshotDto snapshot) => new()
        {
            Snapshot = snapshot,
            Error = new ${name}BridgeErrorDto { Failure = failure, Code = code, Diagnostic = diagnostic }
        };
    }
}
`;
}

function bridgeTests(operation: Operation, profile: UnityTargetProfile): string {
  const name = identifier(operation.id);
  return `// Generated by crdd-ir. Do not edit.
#if UNITY_INCLUDE_TESTS
using NUnit.Framework;

namespace ${profile.namespace}.Tests
{
    public sealed class ${name}BridgeGeneratedTests
    {
        private sealed class FailingAdapter : I${name}ProductAdapter
        {
            public bool RequestSucceeds;
            public int CommitCalls;
            public bool TryBuildRequest(out ${name}BridgeRequestDto request, out string diagnostic)
            {
                request = new();
                diagnostic = "request rejected";
                return RequestSucceeds;
            }
            public bool TryLoadSnapshot(out ${name}BridgeSnapshotDto snapshot, out string diagnostic)
            {
                snapshot = new() { Revision = 41 };
                diagnostic = "load rejected";
                return false;
            }
            public bool TryCommitSnapshot(${name}BridgeSnapshotDto candidate, ulong expectedRevision, out string diagnostic)
            {
                CommitCalls++;
                diagnostic = "unexpected commit";
                return false;
            }
        }

        [Test]
        public void AdapterFailuresNeverCommitAndPreserveLoadedRevision()
        {
            var adapter = new FailingAdapter();
            Assert.That(${name}Bridge.Execute(adapter).Succeeded, Is.False);
            Assert.That(adapter.CommitCalls, Is.Zero);
            adapter.RequestSucceeds = true;
            var loadFailure = ${name}Bridge.Execute(adapter);
            Assert.That(loadFailure.Snapshot.Revision, Is.EqualTo(41UL));
            Assert.That(adapter.CommitCalls, Is.Zero);
        }
    }
}
#endif
`;
}

function objectClass(
  operationName: string,
  scope: string,
  fieldName: string,
  field: Extract<FieldDefinition, { type: "object" }>,
): string {
  const className = `${operationName}${scope}${identifier(fieldName)}`;
  return objectClassNamed(className, field, operationName, scope);
}

function objectClassNamed(
  className: string,
  field: Extract<FieldDefinition, { type: "object" }>,
  operationName: string,
  scope = "",
): string {
  return `public sealed class ${className}
{
${Object.entries(field.properties).map(([name, child]) =>
  `    public ${csType(child, operationName, scope, name)} ${csField(name, child)} = ${csDefault(child)};`
).join("\n")}
}`;
}

function unionClasses(
  operationName: string,
  scope: string,
  fieldName: string,
  field: Extract<FieldDefinition, { type: "union" }>,
): string {
  const base = `${operationName}${scope}${identifier(fieldName)}Union`;
  const variants = field.variants.map((variant) => unionVariant(field, variant));
  const payloads = field.variants.map((variant, index) => {
    const variantName = identifier(variants[index]);
    return `public sealed class ${base}${variantName}Payload
{
${Object.entries(variant.properties)
  .filter(([property]) => property !== field.discriminator)
  .map(([property, child]) =>
    `    public ${csType(child, operationName, `${scope}${identifier(fieldName)}${variantName}`, property)} ${csField(property, child)} = ${csDefault(child)};`
  ).join("\n")}
}`;
  }).join("\n\n");
  return `${payloads}

public enum ${base}Variant
{
    Unknown,
${variants.map((variant) => `    ${identifier(variant)},`).join("\n")}
}

public sealed class ${base}
{
    public ${base}Variant Variant;
${variants.map((variant) => {
  const variantName = identifier(variant);
  return `    public ${base}${variantName}Payload ${variantName} = new();`;
}).join("\n")}
}`;
}

function unionVariant(
  union: Extract<FieldDefinition, { type: "union" }>,
  variant: Extract<FieldDefinition, { type: "object" }>,
): string {
  const discriminator = variant.properties[union.discriminator];
  if (discriminator.type !== "string" || discriminator.enum?.length !== 1) {
    throw new Error(`Union discriminator "${union.discriminator}" must have one string value`);
  }
  return discriminator.enum[0];
}

function csEffect(effect: Effect, operation: Operation): string {
  const body = csEffectBody(effect, operation);
  const trace = effect.traces?.length
    ? `\n            result.Traces = result.Traces.Concat(new[] { ${effect.traces.map((item) => `"${escape(item)}"`).join(", ")} }).ToArray();`
    : "";
  if (!effect.when) return `${body}${trace}`;
  return `            if (${csExpression(effect.when, operation, "result.State")})
            {
${indent(`${body}${trace}`, 4)}
            }`;
}

function csEffectBody(effect: Effect, operation: Operation): string {
  if (effect.action === "assign") {
    const crossScope = csCrossScopeAssignment(effect, operation);
    if (crossScope) return crossScope;
    const expression = csExpression(effect.expression, operation, "result.State");
    const targetField = referenceField(effect.target, operation);
    const value = targetField.type === "number"
      ? `checked(${expression})`
      : targetField.type === "opaque"
        ? `CloneOpaque(${expression})`
        : expression;
    return `            ${csReference(effect.target, operation, "result.State")} = ${value};`;
  }
  if (effect.action === "increment") {
    return `            ${csReference(effect.target, operation, "result.State")} = checked(${csReference(effect.target, operation, "result.State")} + ${csExpression(effect.expression, operation, "result.State")});`;
  }
  const target = csReference(effect.target, operation, "result.State");
  const stateName = effect.target.slice("state.".length);
  const field = operation.state[stateName];
  if (field?.type !== "array") throw new Error(`Unity array effect target "${effect.target}" is not an array`);
  if (effect.action === "append") {
    const value = effect.value as Record<string, unknown>;
    return `            ${target}.Add(new ${identifier(operation.id)}${identifier(stateName)}Item
            {
${Object.keys(field.items.properties).map((key) =>
  `                ${csField(key, field.items.properties[key])} = ${csValue(value[key], operation, "result.State")},`
).join("\n")}
            });`;
  }
  const predicate = Object.entries(effect.where)
    .map(([key, value]) => `item.${csField(key, field.items.properties[key])} == ${csValue(value, operation, "result.State")}`)
    .join(" && ");
  if (effect.action === "remove") return `            ${target}.RemoveAll(item => ${predicate});`;
  return `            foreach (var item in ${target})
            {
                if (${predicate})
                {
${Object.entries(effect.set).map(([key, value]) =>
  `                    item.${csField(key, field.items.properties[key])} = ${csValue(value, operation, "result.State")};`
).join("\n")}
                }
            }`;
}

function referenceField(reference: string, operation: Operation): FieldDefinition {
  const [scope, ...parts] = reference.split(".");
  const fields = scope === "input" ? operation.input : operation.state;
  const relative = parts.join(".");
  if (fields[relative]) return fields[relative];
  let field = fields[parts[0]];
  if (!field) throw new Error(`Unknown Unity reference "${reference}"`);
  for (const part of parts.slice(1)) {
    if (field.type !== "object" || !field.properties[part]) {
      throw new Error(`Unknown Unity reference "${reference}"`);
    }
    field = field.properties[part];
  }
  return field;
}

function stateCloneAssignments(operation: Operation): string {
  return Object.entries(operation.state).map(([name, field]) => {
    const destination = csField(name, field);
    return `            ${destination} = ${csDeepCloneValue(
      field,
      `source.${destination}`,
      identifier(operation.id),
      "State",
      name,
    )},`;
  }).join("\n");
}

function csDeepCloneValue(
  field: FieldDefinition,
  access: string,
  operationName: string,
  scope: string,
  name: string,
  explicitObjectType?: string,
): string {
  if (field.type === "array") {
    if (field.items.type === "object") {
      const itemType = csCollectionItemType(field, operationName, name);
      return `${access}.ConvertAll(item => ${csDeepCloneValue(
        field.items,
        "item",
        operationName,
        "",
        `${name}Item`,
        itemType,
      )})`;
    }
    const itemType = csType(field.items, operationName, `${scope}${identifier(name)}Item`, "Value");
    return `${access}.ConvertAll(item => ${csDeepCloneValue(
      field.items,
      "item",
      operationName,
      `${scope}${identifier(name)}Item`,
      "Value",
    )})`;
  }
  if (field.type === "object") {
    const objectType = explicitObjectType ?? `${operationName}${scope}${identifier(name)}`;
    const assignments = Object.entries(field.properties).map(([childName, child]) =>
      `${csField(childName, child)} = ${csDeepCloneValue(
        child,
        `${access}.${csField(childName, child)}`,
        operationName,
        `${scope}${identifier(name)}`,
        childName,
      )}`
    ).join(", ");
    return `new ${objectType} { ${assignments} }`;
  }
  if (field.type === "map") {
    if (field.values.type !== "object") throw new Error(`Unity map "${name}" must contain objects`);
    const itemType = csCollectionItemType(field, operationName, name);
    return `${access}.ToDictionary(pair => pair.Key, pair => ${csDeepCloneValue(
      field.values,
      "pair.Value",
      operationName,
      "",
      `${name}Item`,
      itemType,
    )})`;
  }
  if (field.type === "opaque") return `CloneOpaque(${access})`;
  if (field.type === "union") return `Clone${identifier(name)}Union(${access})`;
  return access;
}

function csCrossScopeAssignment(effect: Effect, operation: Operation): string | undefined {
  const targetMatch = effect.target.match(/^state\.([A-Za-z_]\w*)$/);
  const sourceMatch = effect.expression.match(/^input\.([A-Za-z_]\w*)$/);
  if (!targetMatch || !sourceMatch) return undefined;
  const target = operation.state[targetMatch[1]];
  const source = operation.input[sourceMatch[1]];
  if (!target || !source || target.type !== source.type) return undefined;
  const left = `result.State.${csField(targetMatch[1], target)}`;
  const right = `input.${csField(sourceMatch[1], source)}`;
  if (target.type === "array" && source.type === "array") {
    return `            ${left} = ${csDeepCloneValue(
      target,
      right,
      identifier(operation.id),
      "State",
      targetMatch[1],
    )};`;
  }
  if (target.type === "map" && source.type === "map") {
    return `            ${left} = ${csDeepCloneValue(
      target,
      right,
      identifier(operation.id),
      "State",
      targetMatch[1],
    )};`;
  }
  if (target.type === "object" && source.type === "object") {
    return `            ${left} = ${csDeepCloneValue(
      target,
      right,
      identifier(operation.id),
      "State",
      targetMatch[1],
    )};`;
  }
  if (target.type === "union" && source.type === "union") {
    const stateType = `${identifier(operation.id)}State${identifier(targetMatch[1])}Union`;
    const inputType = `${identifier(operation.id)}Input${identifier(sourceMatch[1])}Union`;
    const cases = target.variants.map((variant) => {
      const variantName = identifier(unionVariant(target, variant));
      const sourceVariant = source.variants.find((item) => unionVariant(source, item) === unionVariant(target, variant));
      if (!sourceVariant) throw new Error(`Union effect variant "${unionVariant(target, variant)}" is missing from input`);
      const payload = Object.keys(variant.properties).filter((name) => name !== target.discriminator)
        .map((name) => `${csField(name, variant.properties[name])} = ${right}.${variantName}.${csField(name, sourceVariant.properties[name])}`)
        .join(", ");
      return `                ${inputType}Variant.${variantName} => new ${stateType}
                {
                    Variant = ${stateType}Variant.${variantName},
                    ${variantName} = new ${stateType}${variantName}Payload { ${payload} }
                },`;
    }).join("\n");
    return `            ${left} = ${right}.Variant switch
            {
${cases}
                _ => new ${stateType} { Variant = ${stateType}Variant.Unknown }
            };`;
  }
  return undefined;
}

function objectLiteral(
  values: Record<string, unknown>,
  fields: Record<string, FieldDefinition>,
  typeName: string,
  operationName: string,
  scope: string,
): string {
  const assignments = Object.entries(fields).map(([name, field]) => {
    const value = values[name];
    return `${csField(name, field)} = ${typedLiteral(value, field, operationName, scope, name)}`;
  }).join(", ");
  return `new ${typeName} { ${assignments} }`;
}

function typedLiteral(
  value: unknown,
  field: FieldDefinition,
  operationName: string,
  scope: string,
  name: string,
): string {
  if (field.type === "array") {
    const items = Array.isArray(value) ? value : [];
    if (field.items.type !== "object") {
      const itemType = csType(field.items, operationName, `${scope}${identifier(name)}Item`, "Value");
      return `new List<${itemType}> { ${items.map((item) =>
        typedLiteral(item, field.items, operationName, `${scope}${identifier(name)}Item`, "Value")
      ).join(", ")} }`;
    }
    const itemType = csCollectionItemType(field, operationName, name);
    return `new List<${itemType}> { ${items.map((item) =>
      objectLiteral(
        item as Record<string, unknown>,
        field.items.properties,
        itemType,
        operationName,
        "",
      )
    ).join(", ")} }`;
  }
  if (field.type === "object") {
    return objectLiteral(
      (value ?? {}) as Record<string, unknown>,
      field.properties,
      `${operationName}${scope}${identifier(name)}`,
      operationName,
      scope,
    );
  }
  if (field.type === "map") {
    if (field.values.type !== "object") throw new Error(`Unity collection "${name}" must contain objects`);
    const entries = value && typeof value === "object" && !Array.isArray(value)
      ? Object.entries(value as Record<string, unknown>).sort(([left], [right]) => left.localeCompare(right))
      : [];
    const itemType = csCollectionItemType(field, operationName, name);
    return `new Dictionary<string, ${itemType}> { ${entries.map(([key, item]) =>
      `["${escape(key)}"] = ${objectLiteral(item as Record<string, unknown>, field.values.properties, itemType, operationName, "")}`
    ).join(", ")} }`;
  }
  if (field.type === "opaque") {
    const opaque = (value ?? {}) as Record<string, unknown>;
    return `new CrddOpaqueValue { Base64 = "${escape(String(opaque.base64 ?? ""))}", Sha256 = "${escape(String(opaque.sha256 ?? ""))}", Active = ${opaque.active ? "true" : "false"} }`;
  }
  if (field.type === "union") {
    const record = value && typeof value === "object" && !Array.isArray(value)
      ? value as Record<string, unknown>
      : {};
    const discriminator = String(record[field.discriminator] ?? "");
    const variant = field.variants.find((candidate) => unionVariant(field, candidate) === discriminator);
    const typeName = `${operationName}${scope}${identifier(name)}Union`;
    if (!variant) return `new ${typeName} { Variant = ${typeName}Variant.Unknown }`;
    const variantName = identifier(discriminator);
    const payloadType = `${typeName}${variantName}Payload`;
    const assignments = Object.entries(variant.properties)
      .filter(([property]) => property !== field.discriminator)
      .map(([property, child]) =>
        `${csField(property, child)} = ${typedLiteral(record[property], child, operationName, `${scope}${identifier(name)}${variantName}`, property)}`
      ).join(", ");
    return `new ${typeName} { Variant = ${typeName}Variant.${variantName}, ${variantName} = new ${payloadType} { ${assignments} } }`;
  }
  if (typeof value === "string") return `"${escape(value)}"`;
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") {
    const projected = (field as FieldDefinition & { _crddCsharpType?: string })._crddCsharpType;
    return projected === "long"
      ? `${Math.trunc(value)}L`
      : projected === "int"
        ? String(Math.trunc(value))
        : projected === "double"
          ? `${value}d`
          : String(value);
  }
  return csDefault(field);
}

function stateAssertions(
  values: Record<string, unknown>,
  fields: Record<string, FieldDefinition>,
  actualRoot: string,
  label: string,
): string[] {
  const lines: string[] = [];
  for (const [name, field] of Object.entries(fields)) {
    const actual = `${actualRoot}.${csField(name, field)}`;
    const value = values[name];
    if (field.type === "array") {
      const items = Array.isArray(value) ? value : [];
      lines.push(`            Assert.That(${actual}.Count, Is.EqualTo(${items.length}), "${escape(label)} ${name} count");`);
      if (field.items.type === "object") {
        items.forEach((item, index) => {
          lines.push(...stateAssertions(
            item as Record<string, unknown>,
            field.items.properties,
            `${actual}[${index}]`,
            `${label} ${name}[${index}]`,
          ));
        });
      } else {
        items.forEach((item, index) => lines.push(
          `            Assert.That(${actual}[${index}], Is.EqualTo(${typedLiteral(item, field.items, "", "", name)}), "${escape(label)} ${name}[${index}]");`,
        ));
      }
    } else if (field.type === "map") {
      if (field.values.type !== "object") throw new Error(`Unity map "${name}" must contain objects`);
      const entries = value && typeof value === "object" && !Array.isArray(value)
        ? Object.entries(value as Record<string, unknown>).sort(([left], [right]) => left.localeCompare(right))
        : [];
      lines.push(`            Assert.That(${actual}.Count, Is.EqualTo(${entries.length}), "${escape(label)} ${name} count");`);
      for (const [key, item] of entries) {
        lines.push(`            Assert.That(${actual}.ContainsKey("${escape(key)}"), Is.True, "${escape(label)} ${name} key");`);
        lines.push(...stateAssertions(
          item as Record<string, unknown>,
          field.values.properties,
          `${actual}["${escape(key)}"]`,
          `${label} ${name}[${key}]`,
        ));
      }
    } else if (field.type === "object") {
      lines.push(...stateAssertions(
        (value ?? {}) as Record<string, unknown>,
        field.properties,
        actual,
        `${label} ${name}`,
      ));
    } else if (field.type === "opaque") {
      const opaque = (value ?? {}) as Record<string, unknown>;
      lines.push(
        `            Assert.That(${actual}.Base64, Is.EqualTo("${escape(String(opaque.base64 ?? ""))}"), "${escape(label)} ${name} base64");`,
        `            Assert.That(${actual}.Sha256, Is.EqualTo("${escape(String(opaque.sha256 ?? ""))}"), "${escape(label)} ${name} sha256");`,
        `            Assert.That(${actual}.Active, Is.${opaque.active ? "True" : "False"}, "${escape(label)} ${name} active");`,
      );
    } else if (field.type === "union") {
      const record = (value ?? {}) as Record<string, unknown>;
      const discriminator = String(record[field.discriminator] ?? "");
      const variant = field.variants.find((candidate) => unionVariant(field, candidate) === discriminator);
      const variantName = variant ? identifier(discriminator) : "Unknown";
      lines.push(
        `            Assert.That(${actual}.Variant.ToString(), Is.EqualTo("${variantName}"), "${escape(label)} ${name} variant");`,
      );
      if (variant) {
        lines.push(...stateAssertions(
          record,
          Object.fromEntries(Object.entries(variant.properties).filter(([property]) =>
            property !== field.discriminator
          )),
          `${actual}.${variantName}`,
          `${label} ${name}.${variantName}`,
        ));
      }
    } else {
      lines.push(
        `            Assert.That(${actual}, Is.EqualTo(${typedLiteral(value, field, "", "", name)}), "${escape(label)} ${name}");`,
      );
    }
  }
  return lines;
}

function csExpression(expression: string, operation: Operation, stateRoot = "initialState"): string {
  return stripCsOuterParens(csExpressionNode(parseSourceExpression(expression), operation, stateRoot))
    .replace(/\(([^()]+) ([+-]) ([^()]+)\)/g, "$1 $2 $3");
}

function csSemanticAssertions(
  expected: import("./model.ts").SimulationResult,
  operation: Operation,
): string[] {
  const lines: string[] = [];
  if (expected.ok && expected.output !== undefined && operation.output?.type === "object" &&
      typeof expected.output === "object" && expected.output !== null && !Array.isArray(expected.output)) {
    for (const [name, value] of Object.entries(expected.output)) {
      const field = operation.output.properties[name];
      if (field && ["boolean", "integer", "number", "string"].includes(field.type)) {
        lines.push(`            Assert.That(result.Output.${csField(name, field)}, Is.EqualTo(${csFixtureLiteral(value)}));`);
      }
    }
  }
  if (expected.events !== undefined) {
    lines.push(`            Assert.That(result.Events.Count, Is.EqualTo(${expected.events.length}));`);
    expected.events.forEach((event, index) => {
      lines.push(`            Assert.That(result.Events[${index}].Type, Is.EqualTo("${escape(event.type)}"));`);
    });
  }
  return lines;
}

function csFixtureLiteral(value: unknown): string {
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") return String(value);
  if (typeof value === "string") return `"${escape(value)}"`;
  throw new Error(`Unsupported semantic fixture value ${JSON.stringify(value)}`);
}

function stripCsOuterParens(value: string): string {
  if (!value.startsWith("(") || !value.endsWith(")")) return value;
  let depth = 0;
  for (let index = 0; index < value.length; index += 1) {
    if (value[index] === "(") depth += 1;
    else if (value[index] === ")") depth -= 1;
    if (depth === 0 && index < value.length - 1) return value;
  }
  return value.slice(1, -1);
}

function csSemanticResult(operation: Operation): string {
  const name = identifier(operation.id);
  const lines: string[] = [];
  if (operation.returns !== undefined) {
    if (operation.output?.type !== "object" || !isCsExpressionRecord(operation.returns)) throw new Error("Unity executable output requires object mapping");
    for (const [fieldName, expression] of Object.entries(operation.returns)) {
      if (typeof expression !== "string" || !operation.output.properties[fieldName]) throw new Error(`Invalid output mapping ${fieldName}`);
      lines.push(`            result.Output.${csField(fieldName, operation.output.properties[fieldName])} = ${csExpression(expression, operation, "result.State")};`);
    }
  }
  const executable = (operation.emits ?? []).filter((event) => event.value !== undefined);
  if (executable.length) lines.push(`            var events = new List<${name}Event>();`);
  for (const event of executable) {
    if (event.payload?.type !== "object" || !isCsExpressionRecord(event.value)) throw new Error(`Invalid event mapping ${event.type}`);
    const condition = event.when ? csExpression(event.when, operation, "result.State") : "true";
    lines.push(`            if (${condition})\n            {`, `                var item = new ${name}Event { Type = "${escape(event.type)}" };`);
    for (const [fieldName, expression] of Object.entries(event.value)) {
      if (typeof expression !== "string" || !event.payload.properties[fieldName]) throw new Error(`Invalid event payload mapping ${fieldName}`);
      lines.push(`                item.${identifier(event.type)}.${csField(fieldName, event.payload.properties[fieldName])} = ${csExpression(expression, operation, "result.State")};`);
    }
    lines.push("                events.Add(item);", "            }");
  }
  if (executable.length) lines.push("            result.Events = events;");
  return lines.join("\n");
}

function isCsExpressionRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function csExpressionNode(
  node: ExpressionNode,
  operation: Operation,
  stateRoot: string,
  itemField?: FieldDefinition,
): string {
  if (node.kind === "literal") return typeof node.value === "string" ? JSON.stringify(node.value) : String(node.value).toLowerCase();
  if (node.kind === "reference") {
    if (node.path.startsWith("item.")) {
      if (!itemField) throw new Error(`Item reference outside collection predicate: ${node.path}`);
      const relative = node.path.slice(5);
      if (itemField.type !== "object") return relative === "value" ? "item" : (() => { throw new Error(`Unknown Unity item reference ${node.path}`); })();
      let current: FieldDefinition = itemField;
      let result = "item";
      for (const part of relative.split(".")) {
        if (current.type !== "object" || !current.properties[part]) throw new Error(`Unknown Unity item reference ${node.path}`);
        current = current.properties[part];
        result += `.${csField(part, current)}`;
      }
      return result;
    }
    return csReference(node.path, operation, stateRoot);
  }
  if (node.kind === "unary") return `(${node.operator}${csExpressionNode(node.operand, operation, stateRoot, itemField)})`;
  if (node.kind === "quantifier") {
    if (node.collection.kind !== "reference") throw new Error(`${node.operator} collection must be a reference`);
    const [scope, name] = node.collection.path.split(".");
    const collection = scope === "input" ? operation.input[name] : operation.state[name];
    if (!collection || (collection.type !== "array" && collection.type !== "map")) throw new Error(`${node.operator} requires collection`);
    const item = collection.type === "array" ? collection.items : collection.values;
    const source = csReference(node.collection.path, operation, stateRoot) + (collection.type === "map" ? ".Values" : "");
    return `${source}.${node.operator === "all" ? "All" : "Any"}(item => ${csExpressionNode(node.predicate, operation, stateRoot, item)})`;
  }
  return `(${csExpressionNode(node.left, operation, stateRoot, itemField)} ${node.operator} ${csExpressionNode(node.right, operation, stateRoot, itemField)})`;
}

function csReference(reference: string, operation: Operation, stateRoot: string): string {
  const [scope, ...parts] = reference.split(".");
  const fields = scope === "input" ? operation.input : operation.state;
  const relative = parts.join(".");
  if (fields[relative]) {
    return `${scope === "input" ? "input" : scope === "previous" ? "initialState" : stateRoot}.${csField(relative, fields[relative])}`;
  }
  let field = fields[parts[0]];
  if (!field) throw new Error(`Unknown Unity reference "${reference}"`);
  let result = `${scope === "input" ? "input" : scope === "previous" ? "initialState" : stateRoot}.${csField(parts[0], field)}`;
  for (const part of parts.slice(1)) {
    if (field.type !== "object") throw new Error(`Unknown Unity reference "${reference}"`);
    field = field.properties[part];
    result += `.${csField(part, field)}`;
  }
  return result;
}

function csValue(value: unknown, operation: Operation, stateRoot: string): string {
  if (typeof value === "string" && value.startsWith("$")) return csReference(value.slice(1), operation, stateRoot);
  if (typeof value === "string") return `"${escape(value)}"`;
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") return String(value);
  throw new Error(`Unsupported Unity effect value "${JSON.stringify(value)}"`);
}

function csType(field: FieldDefinition, operation: string, scope: string, name: string): string {
  const projected = (field as FieldDefinition & { _crddCsharpType?: string })._crddCsharpType;
  if (projected) return projected;
  if (field.type === "number") return "double";
  if (field.type === "integer") return "long";
  if (field.type === "string") return "string";
  if (field.type === "boolean") return "bool";
  if (field.type === "object") return `${operation}${scope}${identifier(name)}`;
  if (field.type === "array") {
    return field.items.type === "object"
      ? `List<${csCollectionItemType(field, operation, name)}>`
      : `List<${csType(field.items, operation, `${scope}${identifier(name)}Item`, "Value")}>`;
  }
  if (field.type === "map") return `Dictionary<string, ${csCollectionItemType(field, operation, name)}>`;
  if (field.type === "union") return `${operation}${scope}${identifier(name)}Union`;
  if (field.type === "opaque") return "CrddOpaqueValue";
  throw new Error(`Unsupported Unity field type`);
}

function csCollectionItemType(field: FieldDefinition, operation: string, name: string): string {
  const generated = (field as FieldDefinition & { _crddCsharpCollectionItemType?: string })
    ._crddCsharpCollectionItemType;
  return generated ?? `${operation}${identifier(name)}Item`;
}

function csDefault(field: FieldDefinition): string {
  if (field.type === "array" || field.type === "map") return "new()";
  if (field.type === "object" || field.type === "union") return "new()";
  if (field.type === "opaque") return "new()";
  if (field.default !== undefined) {
    if (typeof field.default === "string") return `"${escape(field.default)}"`;
    if (typeof field.default === "boolean") return field.default ? "true" : "false";
    return String(field.default);
  }
  if (field.type === "string") return '""';
  return field.type === "boolean" ? "false" : "0";
}

function csField(name: string, field: FieldDefinition): string {
  const base = identifier(name);
  return field.unit ? `${base}${identifier(field.unit)}` : base;
}

function projectNumericTypes(operation: Operation, profile: UnityTargetProfile): Operation {
  const result = structuredClone(operation);
  const visit = (field: FieldDefinition): void => {
    if (field.type === "object") Object.values(field.properties).forEach(visit);
    else if (field.type === "array") visit(field.items);
    else if (field.type === "map") visit(field.values);
    else if (field.type === "union") field.variants.forEach(visit);
    else if (field.type === "number" && field.unit && profile.numericProjection?.[field.unit]) {
      (field as FieldDefinition & { _crddCsharpType?: string })._crddCsharpType =
        profile.numericProjection[field.unit].csharpType;
    }
  };
  Object.values(result.input).forEach(visit);
  Object.values(result.state).forEach(visit);
  const collections = ([
    ...Object.entries(result.input).map(([name, field]) => ({ scope: "Input", name, field })),
    ...Object.entries(result.state).map(([name, field]) => ({ scope: "State", name, field })),
  ]).filter(({ field }) =>
    (field.type === "array" && field.items.type === "object") ||
    (field.type === "map" && field.values.type === "object")
  ).sort((left, right) => `${left.scope}:${left.name}`.localeCompare(`${right.scope}:${right.name}`));
  const byShape = new Map<string, string>();
  const usedNames = new Set<string>();
  const operationName = identifier(result.id);
  for (const collection of collections) {
    const item = collection.field.type === "array" ? collection.field.items : collection.field.values;
    const shape = csharpGeneratedFieldShape(item);
    let typeName = byShape.get(shape);
    if (!typeName) {
      const base = `${operationName}${identifier(collection.name)}Item`;
      typeName = base;
      if (usedNames.has(typeName)) typeName = `${operationName}${collection.scope}${identifier(collection.name)}Item`;
      let suffix = 2;
      const unsuffixed = typeName;
      while (usedNames.has(typeName)) typeName = `${unsuffixed}${suffix++}`;
      usedNames.add(typeName);
      byShape.set(shape, typeName);
    }
    (collection.field as FieldDefinition & { _crddCsharpCollectionItemType?: string })
      ._crddCsharpCollectionItemType = typeName;
  }
  return result;
}

function csharpGeneratedFieldShape(field: FieldDefinition): string {
  const projected = (field as FieldDefinition & { _crddCsharpType?: string })._crddCsharpType;
  if (projected) return `projected:${projected}`;
  if (field.type === "object") {
    return `object:{${Object.entries(field.properties).sort(([a], [b]) => a.localeCompare(b))
      .map(([name, child]) => `${name}:${csharpGeneratedFieldShape(child)}`).join(",")}}`;
  }
  if (field.type === "array") return `array:<${csharpGeneratedFieldShape(field.items)}>`;
  if (field.type === "map") return `map:<${csharpGeneratedFieldShape(field.values)}>`;
  if (field.type === "union") {
    return `union:${field.discriminator}:[${field.variants.map(csharpGeneratedFieldShape).join("|")}]`;
  }
  return `${field.type}:${field.unit ?? ""}`;
}

function identifier(value: string): string {
  return value.split(/[^A-Za-z0-9]+/).filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1)).join("");
}

function indent(value: string, spaces: number): string {
  const prefix = " ".repeat(spaces);
  return value.split("\n").map((line) => line ? `${prefix}${line}` : line).join("\n");
}

function escape(value: string): string {
  let escaped = "";
  for (const character of value) {
    const code = character.charCodeAt(0);
    if (character === "\\") escaped += "\\\\";
    else if (character === '"') escaped += '\\"';
    else if (character === "\b") escaped += "\\b";
    else if (character === "\f") escaped += "\\f";
    else if (character === "\n") escaped += "\\n";
    else if (character === "\r") escaped += "\\r";
    else if (character === "\t") escaped += "\\t";
    else if (code <= 0x1f) escaped += `\\u${code.toString(16).padStart(4, "0")}`;
    else escaped += character;
  }
  return escaped;
}
