import { createHash } from "node:crypto";
import type { CrddIr, Effect, FieldDefinition, Operation } from "./model.ts";
import { parseSourceExpression, type ExpressionNode } from "./source-expression.ts";
import { generateTestManifest } from "./test-manifest.ts";
import type { UnrealNumericProjection } from "./unreal-target.ts";
import { generateUnrealBridge } from "./unreal-bridge.ts";

export type GeneratedFile = {
  name: string;
  content: string;
  sha256: string;
};

export function generateUnreal(
  ir: CrddIr,
  metadata: {
    irSha256?: string;
    generatorVersion?: string;
    numericProjection?: Record<string, UnrealNumericProjection>;
  } = {},
): GeneratedFile[] {
  const operation = projectNumericTypes(ir.operation, metadata.numericProjection ?? {});
  const operationName = pascalIdentifier(operation.id);

  const files = [
    { name: `${operationName}.generated.h`, content: generateHeader(operation, metadata) },
    { name: `${operationName}.generated.cpp`, content: generateSource(operation, metadata.numericProjection ?? {}) },
    ...generateUnrealBridge(operation),
    ...(hasIntegerProjection(operation)
      ? [{
          name: `${operationName}.numeric.generated.spec.cpp`,
          content: generateNumericBoundaryFixture(ir, operation),
        }]
      : []),
  ];
  return files.map((file) => ({
    ...file,
    sha256: createHash("sha256").update(file.content).digest("hex"),
  }));
}

function generateHeader(
  operation: Operation,
  metadata: {
    irSha256?: string;
    generatorVersion?: string;
    numericProjection?: Record<string, UnrealNumericProjection>;
  },
): string {
  const operationName = pascalIdentifier(operation.id);
  const traceComment = traces(operation);
  const errorValues = operation.errors
    .map((error) => `    ${pascalCase(error.code)},`)
    .join("\n");
  const arrayStructs = Object.entries(operation.state)
    .filter(([, field]) => field.type === "array")
    .map(([name]) => generateArrayElementStruct(operation, name))
    .join("\n");
  const objectStructs = [
    ...Object.entries(operation.input)
      .filter(([, field]) => field.type === "object")
      .map(([name, field]) => generateObjectStruct(operation, "Input", name, field)),
    ...Object.entries(operation.state)
      .filter(([, field]) => field.type === "object")
      .map(([name, field]) => generateObjectStruct(operation, "State", name, field)),
  ].join("\n");
  const inputFields = Object.entries(operation.input)
    .map(([name, field]) => {
      const type = field.type === "object"
        ? objectStructName(operation, "Input", name)
        : cppType(field);
      return `    ${type} ${cppField(name, field)} = ${cppDefault(field)};`;
    })
    .join("\n");
  const stateFields = Object.entries(operation.state)
    .map(([name, field]) => {
      const type =
        field.type === "array"
          ? `TArray<FCrdd${operationName}${pascalIdentifier(name)}Item>`
          : field.type === "object"
            ? objectStructName(operation, "State", name)
            : cppType(field);
      return `    ${type} ${cppField(name, field)}${field.type === "array" ? "" : ` = ${cppDefault(field)}`};`;
    })
    .join("\n");

  const generationIdentity = metadata.irSha256
    ? `// CRDD-IR Generator: ${metadata.generatorVersion ?? "unknown"}\n` +
      `// CRDD-IR Input SHA-256: ${metadata.irSha256}\n`
    : "";
  const numericIdentity = Object.entries(metadata.numericProjection ?? {})
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([unit, projection]) =>
      `// CRDD-IR Numeric Projection: ${unit} -> ${projection.cppType}, JSON=${projection.jsonRepresentation}, rounding=${projection.rounding}, overflow=${projection.overflow}`
    ).join("\n");
  return `// Generated by crdd-ir. Do not edit.
${generationIdentity}${numericIdentity ? `${numericIdentity}\n` : ""}${traceComment}
#pragma once

#include "CoreMinimal.h"

${arrayStructs}
${objectStructs}

struct FCrdd${operationName}Input
{
${inputFields}
};

struct FCrdd${operationName}State
{
${stateFields}
};

enum class ECrdd${operationName}Error : uint8
{
    None,
${errorValues}
};

struct FCrdd${operationName}Result
{
    bool bSucceeded = false;
    ECrdd${operationName}Error Error = ECrdd${operationName}Error::None;
    FString FailedRequirement;
    FCrdd${operationName}State State;
    TArray<FString> Traces;
};

class FCrdd${operationName}Operation
{
public:
    static FCrdd${operationName}Result Execute(
        const FCrdd${operationName}Input& Input,
        const FCrdd${operationName}State& InitialState
    );

    static FString ErrorCode(ECrdd${operationName}Error Error);
    static bool TryParseProjectedInt64(const FString& Decimal, int64& OutValue);
    static FString SerializeProjectedInt64(int64 Value);
};
`;
}

function generateObjectStruct(
  operation: Operation,
  scope: "Input" | "State",
  name: string,
  field: Extract<FieldDefinition, { type: "object" }>,
): string {
  const fields = Object.entries(field.properties)
    .map(([propertyName, property]) =>
      `    ${cppType(property)} ${cppField(propertyName, property)} = ${cppDefault(property)};`
    )
    .join("\n");
  return `struct ${objectStructName(operation, scope, name)}
{
${fields}
};`;
}

function objectStructName(operation: Operation, scope: "Input" | "State", name: string): string {
  return `FCrdd${pascalIdentifier(operation.id)}${scope}${pascalIdentifier(name)}`;
}

function generateSource(
  operation: Operation,
  _numericProjection: Record<string, UnrealNumericProjection>,
): string {
  const operationName = pascalIdentifier(operation.id);
  const checks = operation.requires
    .map((requirement, requirementIndex) => {
      const error = operation.errors.find((entry) => entry.code === requirement.error);
      if (!error) throw new Error(`Requirement "${requirement.id}" uses unknown error "${requirement.error}"`);
      const compiled = compileCheckedExpression(
        requirement.expression,
        operation,
        "InitialState",
        requirementIndex,
      );
      const guard = compiled.overflowChecks.length > 0
        ? `${compiled.overflowChecks.join(" || ")} || !(${compiled.expression})`
        : `!(${compiled.expression})`;
      return `    // ${requirement.id}: ${requirement.expression}
${compiled.statements.map((statement) => `    ${statement}`).join("\n")}${compiled.statements.length ? "\n" : ""}    if (${guard})
    {
        return Failure(
            ECrdd${operationName}Error::${pascalCase(requirement.error)},
            TEXT("${requirement.id}"),
            InitialState,
            {${error.traces.map((trace) => `TEXT("${trace}")`).join(", ")}}
        );
    }`;
    })
    .join("\n\n");

  const effects = operation.effects.map((effect) => cppEffect(effect, operation)).join("\n");
  const successTraces = operation.traces.map((trace) => `TEXT("${trace}")`).join(", ");
  const errorCases = operation.errors
    .map(
      (error) => `    case ECrdd${operationName}Error::${pascalCase(error.code)}:
        return TEXT("${error.code}");`,
    )
    .join("\n");

  return `// Generated by crdd-ir. Do not edit.
${traces(operation)}
#include "${operationName}.generated.h"

#include <initializer_list>
#include <limits>

namespace
{
bool CrddTryAddInt64(int64 Left, int64 Right, int64& OutValue)
{
    if ((Right > 0 && Left > std::numeric_limits<int64>::max() - Right) ||
        (Right < 0 && Left < std::numeric_limits<int64>::min() - Right))
    {
        return false;
    }
    OutValue = Left + Right;
    return true;
}

bool CrddTrySubtractInt64(int64 Left, int64 Right, int64& OutValue)
{
    if ((Right < 0 && Left > std::numeric_limits<int64>::max() + Right) ||
        (Right > 0 && Left < std::numeric_limits<int64>::min() + Right))
    {
        return false;
    }
    OutValue = Left - Right;
    return true;
}

FCrdd${operationName}Result Failure(
    ECrdd${operationName}Error Error,
    const TCHAR* FailedRequirement,
    const FCrdd${operationName}State& InitialState,
    std::initializer_list<const TCHAR*> FailureTraces
)
{
    FCrdd${operationName}Result Result;
    Result.Error = Error;
    Result.FailedRequirement = FailedRequirement;
    Result.State = InitialState;
    for (const TCHAR* Trace : FailureTraces)
    {
        Result.Traces.Add(Trace);
    }
    return Result;
}
}

FCrdd${operationName}Result FCrdd${operationName}Operation::Execute(
    const FCrdd${operationName}Input& Input,
    const FCrdd${operationName}State& InitialState
)
{
${checks}

    FCrdd${operationName}Result Result;
    Result.bSucceeded = true;
    Result.State = InitialState;
${effects}
    Result.Traces = {${successTraces}};
    return Result;
}

FString FCrdd${operationName}Operation::ErrorCode(ECrdd${operationName}Error Error)
{
    switch (Error)
    {
    case ECrdd${operationName}Error::None:
        return TEXT("");
${errorCases}
    default:
        return TEXT("UNKNOWN");
    }
}

bool FCrdd${operationName}Operation::TryParseProjectedInt64(
    const FString& Decimal,
    int64& OutValue
)
{
    if (Decimal.IsEmpty() || Decimal.TrimStartAndEnd() != Decimal)
    {
        return false;
    }
    if (!LexTryParseString(OutValue, *Decimal))
    {
        return false;
    }
    return LexToString(OutValue) == Decimal;
}

FString FCrdd${operationName}Operation::SerializeProjectedInt64(int64 Value)
{
    return LexToString(Value);
}
`;
}

function hasIntegerProjection(operation: Operation): boolean {
  const contains = (field: FieldDefinition): boolean => {
    if (field.type === "object") return Object.values(field.properties).some(contains);
    if (field.type === "array") return contains(field.items);
    const projected = (field as FieldDefinition & { _crddCppType?: string })._crddCppType;
    return projected === "int32" || projected === "int64";
  };
  return [...Object.values(operation.input), ...Object.values(operation.state)].some(contains);
}

function generateNumericBoundaryFixture(ir: CrddIr, operation: Operation): string {
  const operationName = pascalIdentifier(operation.id);
  const baseline = generateTestManifest(ir).cases.find((item) => item.expect.ok)?.arrange;
  if (!baseline) throw new Error(`Cannot generate numeric fixture for "${operation.id}" without a success baseline`);
  const overflowRequirement = operation.requires
    .map((requirement) => ({
      requirement,
      operands: firstCheckedAddition(parseSourceExpression(requirement.expression), operation),
    }))
    .find((entry) => entry.operands);
  const baselineAssignments = [
    ...primitiveAssignments(baseline.input, "input", operation, "Input"),
    ...primitiveAssignments(baseline.state, "state", operation, "State"),
  ].map((line) => `    ${line}`).join("\n");
  const overflowBlock = overflowRequirement?.operands
    ? `
    ${cppReference(overflowRequirement.operands[0], operation, "State")} =
        std::numeric_limits<int64>::max();
    ${cppReference(overflowRequirement.operands[1], operation, "State")} = 1;
    const FCrdd${operationName}Result Overflow =
        FCrdd${operationName}Operation::Execute(Input, State);
    TestFalse(TEXT("Overflow must not satisfy its requirement"), Overflow.bSucceeded);
    TestEqual(
        TEXT("Overflow identifies its requirement"),
        Overflow.FailedRequirement,
        FString(TEXT("${overflowRequirement.requirement.id}"))
    );
`
    : "";
  return `// Generated by crdd-ir. Do not edit.
#if WITH_DEV_AUTOMATION_TESTS

#include "${operationName}.generated.h"

#include "Misc/AutomationTest.h"
#include <limits>

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
    FCrdd${operationName}NumericBoundaryTest,
    "CRDD.${operationName}.NumericBoundary.Generated",
    EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter
)

bool FCrdd${operationName}NumericBoundaryTest::RunTest(const FString& Parameters)
{
    FCrdd${operationName}Input Input;
    FCrdd${operationName}State State;
${baselineAssignments}
${overflowBlock}
    int64 Parsed = 0;
    TestTrue(
        TEXT("Maximum int64 decimal string parses"),
        FCrdd${operationName}Operation::TryParseProjectedInt64(
            TEXT("9223372036854775807"), Parsed
        )
    );
    TestEqual(TEXT("Maximum int64 is preserved"), Parsed, std::numeric_limits<int64>::max());
    TestEqual(
        TEXT("Maximum int64 round trips"),
        FCrdd${operationName}Operation::SerializeProjectedInt64(Parsed),
        FString(TEXT("9223372036854775807"))
    );
    TestTrue(
        TEXT("Minimum int64 decimal string parses"),
        FCrdd${operationName}Operation::TryParseProjectedInt64(
            TEXT("-9223372036854775808"), Parsed
        )
    );
    TestFalse(
        TEXT("Overflowing decimal string is rejected"),
        FCrdd${operationName}Operation::TryParseProjectedInt64(
            TEXT("9223372036854775808"), Parsed
        )
    );
    TestFalse(
        TEXT("Underflowing decimal string is rejected"),
        FCrdd${operationName}Operation::TryParseProjectedInt64(
            TEXT("-9223372036854775809"), Parsed
        )
    );
    TestFalse(
        TEXT("Lossy decimal value is rejected"),
        FCrdd${operationName}Operation::TryParseProjectedInt64(TEXT("1.5"), Parsed)
    );
    TestFalse(
        TEXT("Non-canonical whitespace is rejected"),
        FCrdd${operationName}Operation::TryParseProjectedInt64(TEXT(" 1"), Parsed)
    );
    return true;
}

#endif
`;
}

function firstCheckedAddition(
  node: ExpressionNode,
  operation: Operation,
): [string, string] | undefined {
  if (node.kind !== "binary") return undefined;
  if (
    (node.operator === "+" || node.operator === "-") &&
    node.left.kind === "reference" &&
    node.right.kind === "reference" &&
    ["int32", "int64"].includes(cppType(referenceField(node.left.path, operation))) &&
    ["int32", "int64"].includes(cppType(referenceField(node.right.path, operation)))
  ) {
    return [node.left.path, node.right.path];
  }
  return firstCheckedAddition(node.left, operation) ??
    firstCheckedAddition(node.right, operation);
}

function primitiveAssignments(
  values: Record<string, unknown>,
  scope: "input" | "state",
  operation: Operation,
  stateRoot: string,
): string[] {
  const result: string[] = [];
  const visit = (value: unknown, path: string): void => {
    if (Array.isArray(value) || (typeof value === "object" && value !== null)) {
      if (Array.isArray(value)) return;
      for (const [name, child] of Object.entries(value)) visit(child, `${path}.${name}`);
      return;
    }
    const literal = typeof value === "string"
      ? `TEXT(${JSON.stringify(value)})`
      : typeof value === "boolean"
        ? (value ? "true" : "false")
        : String(value);
    result.push(`${cppReference(path, operation, stateRoot)} = ${literal};`);
  };
  for (const [name, value] of Object.entries(values)) visit(value, `${scope}.${name}`);
  return result;
}

type CheckedCppExpression = {
  expression: string;
  statements: string[];
  overflowChecks: string[];
  integer: boolean;
};

function compileCheckedExpression(
  expression: string,
  operation: Operation,
  stateRoot: string,
  requirementIndex: number,
): CheckedCppExpression {
  let temporaryIndex = 0;
  const compile = (node: ExpressionNode): CheckedCppExpression => {
    if (node.kind === "reference") {
      const field = referenceField(node.path, operation);
      return {
        expression: cppReference(node.path, operation, stateRoot),
        statements: [],
        overflowChecks: [],
        integer: cppType(field) === "int32" || cppType(field) === "int64",
      };
    }
    if (node.kind === "literal") {
      return {
        expression: typeof node.value === "string"
          ? `TEXT(${JSON.stringify(node.value)})`
          : String(node.value),
        statements: [],
        overflowChecks: [],
        integer: typeof node.value === "number" && Number.isInteger(node.value),
      };
    }
    if (node.kind === "unary") {
      const operand = compile(node.operand);
      return { ...operand, expression: `(${node.operator}${operand.expression})` };
    }
    const left = compile(node.left);
    const right = compile(node.right);
    const statements = [...left.statements, ...right.statements];
    const overflowChecks = [...left.overflowChecks, ...right.overflowChecks];
    if ((node.operator === "+" || node.operator === "-") && left.integer && right.integer) {
      const name = `CrddChecked${requirementIndex}_${temporaryIndex++}`;
      const overflow = `bCrddOverflow${requirementIndex}_${temporaryIndex}`;
      statements.push(`int64 ${name} = 0;`);
      statements.push(
        `const bool ${overflow} = !${node.operator === "+" ? "CrddTryAddInt64" : "CrddTrySubtractInt64"}(` +
        `${left.expression}, ${right.expression}, ${name});`,
      );
      overflowChecks.push(overflow);
      return { expression: name, statements, overflowChecks, integer: true };
    }
    return {
      expression: `(${left.expression} ${node.operator} ${right.expression})`,
      statements,
      overflowChecks,
      integer: false,
    };
  };
  return compile(parseSourceExpression(expression));
}

function cppEffect(effect: Effect, operation: Operation): string {
  if (effect.action === "assign") {
    return `    ${cppReference(effect.target, operation, "Result.State")} = ${cppExpression(
      effect.expression,
      operation,
      "Result.State",
    )};`;
  }
  if (effect.action === "increment") {
    return `    ${cppReference(effect.target, operation, "Result.State")} += ${cppExpression(
      effect.expression,
      operation,
      "Result.State",
    )};`;
  }

  if (!effect.target.startsWith("state.")) throw new Error("Unreal array effect target must be state");
  const stateName = effect.target.slice("state.".length);
  if (operation.state[stateName]?.type !== "array") {
    throw new Error(`Unreal ${effect.action} target "${effect.target}" is not an array`);
  }
  const arrayField = operation.state[stateName];
  if (arrayField.type !== "array") throw new Error(`Unreal ${effect.action} target is not an array`);
  const collection = `Result.State.${cppField(stateName, arrayField)}`;
  const itemType = `FCrdd${pascalIdentifier(operation.id)}${pascalIdentifier(stateName)}Item`;
  if (effect.action === "remove" || effect.action === "update") {
    const condition = cppItemMatch(effect.where, arrayField.items.properties, operation);
    if (effect.action === "remove") {
      return `    ${collection}.RemoveAll([&](const ${itemType}& Item)
    {
        return ${condition};
    });`;
    }
    const assignments = Object.entries(effect.set)
      .map(([name, value]) =>
        `            Item.${cppField(name, arrayField.items.properties[name])} = ` +
        `${cppEffectValue(value, operation)};`
      )
      .join("\n");
    return `    for (${itemType}& Item : ${collection})
    {
        if (${condition})
        {
${assignments}
        }
    }`;
  }

  const value = effect.value as Record<string, unknown>;
  const values = Object.keys(arrayField.items.properties)
    .map((name) => cppEffectValue(value[name], operation))
    .join(", ");
  return `    ${collection}.Add({${values}});`;
}

function cppItemMatch(
  where: Record<string, unknown>,
  properties: Record<string, FieldDefinition>,
  operation: Operation,
): string {
  return Object.entries(where)
    .map(([name, value]) =>
      `Item.${cppField(name, properties[name])} == ${cppEffectValue(value, operation)}`
    )
    .join(" && ");
}

function generateArrayElementStruct(operation: Operation, stateName: string): string {
  const operationName = pascalIdentifier(operation.id);
  const arrayField = operation.state[stateName];
  if (arrayField?.type !== "array") throw new Error(`Unreal state "${stateName}" is not an array`);
  const fields = Object.entries(arrayField.items.properties)
    .map(([name, field]) => {
      return `    ${cppType(field)} ${cppField(name, field)} = ${cppDefault(field)};`;
    })
    .join("\n");
  return `struct FCrdd${operationName}${pascalIdentifier(stateName)}Item
{
${fields}
};`;
}

function cppExpression(expression: string, operation: Operation, stateRoot: string): string {
  return expression
    .replace(/"(?:[^"\\]|\\.)*"/g, (literal) => `TEXT(${literal})`)
    .replace(/\b(?:input|state)\.[A-Za-z_][A-Za-z0-9_.]*/g, (reference) =>
      cppReference(reference, operation, stateRoot),
    );
}

function cppEffectValue(value: unknown, operation: Operation): string {
  if (typeof value === "string" && value.startsWith("$")) {
    return cppReference(value.slice(1), operation, "Result.State");
  }
  if (typeof value === "string") return `TEXT(${JSON.stringify(value)})`;
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number" && Number.isFinite(value)) return value.toString();
  throw new Error(`Unsupported Unreal append value "${JSON.stringify(value)}"`);
}

function cppReference(reference: string, operation: Operation, stateRoot: string): string {
  if (reference.startsWith("input.")) {
    const relative = reference.slice("input.".length);
    const exact = operation.input[relative];
    if (exact) return `Input.${cppField(relative, exact)}`;
    const [name, ...properties] = relative.split(".");
    let field = operation.input[name];
    if (!field) throw new Error(`Unknown Unreal input reference "${reference}"`);
    let result = `Input.${cppField(name, field)}`;
    for (const propertyName of properties) {
      if (field.type !== "object" || !field.properties[propertyName]) {
        throw new Error(`Unknown Unreal input reference "${reference}"`);
      }
      field = field.properties[propertyName];
      result += `.${cppField(propertyName, field)}`;
    }
    return result;
  }
  if (reference.startsWith("state.")) {
    const relative = reference.slice("state.".length);
    const exact = operation.state[relative];
    if (exact) return `${stateRoot}.${cppField(relative, exact)}`;
    const [name, ...properties] = relative.split(".");
    let field = operation.state[name];
    if (!field) throw new Error(`Unknown Unreal state reference "${reference}"`);
    let result = `${stateRoot}.${cppField(name, field)}`;
    for (const propertyName of properties) {
      if (field.type !== "object" || !field.properties[propertyName]) {
        throw new Error(`Unknown Unreal state reference "${reference}"`);
      }
      field = field.properties[propertyName];
      result += `.${cppField(propertyName, field)}`;
    }
    return result;
  }
  throw new Error(`Unsupported Unreal reference "${reference}"`);
}

function cppField(name: string, field: FieldDefinition): string {
  const base = name.split(".").map(pascalCase).join("");
  return field.unit ? `${base}${pascalCase(field.unit)}` : base;
}

function cppType(field: FieldDefinition): string {
  const projected = (field as FieldDefinition & { _crddCppType?: string })._crddCppType;
  if (projected) return projected;
  if (field.type === "number") return "double";
  if (field.type === "boolean") return "bool";
  if (field.type === "string") return "FString";
  throw new Error(`Unsupported generated field type "${field.type}"`);
}

function cppDefault(field: FieldDefinition): string {
  if (field.type !== "array" && field.default !== undefined) {
    if (typeof field.default === "string") return `TEXT(${JSON.stringify(field.default)})`;
    if (typeof field.default === "boolean") return field.default ? "true" : "false";
    return field.default.toString();
  }
  const projected = (field as FieldDefinition & { _crddCppType?: string })._crddCppType;
  if (field.type === "number" && projected?.startsWith("int")) return "0";
  if (field.type === "number") return "0.0";
  if (field.type === "boolean") return "false";
  if (field.type === "string") return 'TEXT("")';
  return "{}";
}

function referenceField(reference: string, operation: Operation): FieldDefinition {
  const [scope, ...segments] = reference.split(".");
  const fields = scope === "input"
    ? operation.input
    : scope === "state"
      ? operation.state
      : undefined;
  if (!fields) throw new Error(`Unknown Unreal reference "${reference}"`);
  const relative = segments.join(".");
  if (fields[relative]) return fields[relative];
  const [name, ...properties] = segments;
  let field = fields[name];
  if (!field) throw new Error(`Unknown Unreal reference "${reference}"`);
  for (const property of properties) {
    if (field.type !== "object" || !field.properties[property]) {
      throw new Error(`Unknown Unreal reference "${reference}"`);
    }
    field = field.properties[property];
  }
  return field;
}

function projectNumericTypes(
  operation: Operation,
  projections: Record<string, UnrealNumericProjection>,
): Operation {
  const result = structuredClone(operation);
  const visit = (field: FieldDefinition): void => {
    if (field.type === "object") {
      Object.values(field.properties).forEach(visit);
    } else if (field.type === "array") {
      visit(field.items);
    } else if (field.type === "number" && field.unit && projections[field.unit]) {
      (field as FieldDefinition & { _crddCppType?: string })._crddCppType =
        projections[field.unit].cppType;
    }
  };
  Object.values(result.input).forEach(visit);
  Object.values(result.state).forEach(visit);
  return result;
}

function traces(operation: Operation): string {
  return operation.traces.map((trace) => `// CRDD-TRACE: ${trace}`).join("\n");
}

function pascalCase(value: string): string {
  return value
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1).toLowerCase())
    .join("");
}

function pascalIdentifier(value: string): string {
  if (!/[^A-Za-z0-9]/.test(value)) {
    return value[0].toUpperCase() + value.slice(1);
  }
  return pascalCase(value);
}
