import { createHash } from "node:crypto";
import type { CrddIr, Effect, FieldDefinition, Operation } from "./model.ts";

export type GeneratedFile = {
  name: string;
  content: string;
  sha256: string;
};

export function generateUnreal(ir: CrddIr): GeneratedFile[] {
  const operation = ir.operation;
  const operationName = pascalIdentifier(operation.id);

  const files = [
    { name: `${operationName}.generated.h`, content: generateHeader(operation) },
    { name: `${operationName}.generated.cpp`, content: generateSource(operation) },
  ];
  return files.map((file) => ({
    ...file,
    sha256: createHash("sha256").update(file.content).digest("hex"),
  }));
}

function generateHeader(operation: Operation): string {
  const operationName = pascalIdentifier(operation.id);
  const traceComment = traces(operation);
  const errorValues = operation.errors
    .map((error) => `    ${pascalCase(error.code)},`)
    .join("\n");
  const arrayStructs = Object.entries(operation.state)
    .filter(([, field]) => field.type === "array")
    .map(([name]) => generateArrayElementStruct(operation, name))
    .join("\n");
  const inputFields = Object.entries(operation.input)
    .map(([name, field]) => `    ${cppType(field)} ${cppField(name, field)} = ${cppDefault(field)};`)
    .join("\n");
  const stateFields = Object.entries(operation.state)
    .map(([name, field]) => {
      const type =
        field.type === "array"
          ? `TArray<FCrdd${operationName}${pascalIdentifier(name)}Item>`
          : cppType(field);
      return `    ${type} ${cppField(name, field)}${field.type === "array" ? "" : ` = ${cppDefault(field)}`};`;
    })
    .join("\n");

  return `// Generated by crdd-ir. Do not edit.
${traceComment}
#pragma once

#include "CoreMinimal.h"

${arrayStructs}

struct FCrdd${operationName}Input
{
${inputFields}
};

struct FCrdd${operationName}State
{
${stateFields}
};

enum class ECrdd${operationName}Error : uint8
{
    None,
${errorValues}
};

struct FCrdd${operationName}Result
{
    bool bSucceeded = false;
    ECrdd${operationName}Error Error = ECrdd${operationName}Error::None;
    FString FailedRequirement;
    FCrdd${operationName}State State;
    TArray<FString> Traces;
};

class FCrdd${operationName}Operation
{
public:
    static FCrdd${operationName}Result Execute(
        const FCrdd${operationName}Input& Input,
        const FCrdd${operationName}State& InitialState
    );

    static FString ErrorCode(ECrdd${operationName}Error Error);
};
`;
}

function generateSource(operation: Operation): string {
  const operationName = pascalIdentifier(operation.id);
  const checks = operation.requires
    .map((requirement) => {
      const error = operation.errors.find((entry) => entry.code === requirement.error);
      if (!error) throw new Error(`Requirement "${requirement.id}" uses unknown error "${requirement.error}"`);
      return `    // ${requirement.id}: ${requirement.expression}
    if (!(${cppExpression(requirement.expression, operation, "InitialState")}))
    {
        return Failure(
            ECrdd${operationName}Error::${pascalCase(requirement.error)},
            TEXT("${requirement.id}"),
            InitialState,
            {${error.traces.map((trace) => `TEXT("${trace}")`).join(", ")}}
        );
    }`;
    })
    .join("\n\n");

  const effects = operation.effects.map((effect) => cppEffect(effect, operation)).join("\n");
  const successTraces = operation.traces.map((trace) => `TEXT("${trace}")`).join(", ");
  const errorCases = operation.errors
    .map(
      (error) => `    case ECrdd${operationName}Error::${pascalCase(error.code)}:
        return TEXT("${error.code}");`,
    )
    .join("\n");

  return `// Generated by crdd-ir. Do not edit.
${traces(operation)}
#include "Generated/${operationName}.generated.h"

#include <initializer_list>

namespace
{
FCrdd${operationName}Result Failure(
    ECrdd${operationName}Error Error,
    const TCHAR* FailedRequirement,
    const FCrdd${operationName}State& InitialState,
    std::initializer_list<const TCHAR*> FailureTraces
)
{
    FCrdd${operationName}Result Result;
    Result.Error = Error;
    Result.FailedRequirement = FailedRequirement;
    Result.State = InitialState;
    for (const TCHAR* Trace : FailureTraces)
    {
        Result.Traces.Add(Trace);
    }
    return Result;
}
}

FCrdd${operationName}Result FCrdd${operationName}Operation::Execute(
    const FCrdd${operationName}Input& Input,
    const FCrdd${operationName}State& InitialState
)
{
${checks}

    FCrdd${operationName}Result Result;
    Result.bSucceeded = true;
    Result.State = InitialState;
${effects}
    Result.Traces = {${successTraces}};
    return Result;
}

FString FCrdd${operationName}Operation::ErrorCode(ECrdd${operationName}Error Error)
{
    switch (Error)
    {
    case ECrdd${operationName}Error::None:
        return TEXT("");
${errorCases}
    default:
        return TEXT("UNKNOWN");
    }
}
`;
}

function cppEffect(effect: Effect, operation: Operation): string {
  if (effect.action === "assign") {
    return `    ${cppReference(effect.target, operation, "Result.State")} = ${cppExpression(
      effect.expression,
      operation,
      "Result.State",
    )};`;
  }

  if (!effect.target.startsWith("state.") || typeof effect.value !== "object" || effect.value === null) {
    throw new Error("Unreal MVP only supports object append to state arrays");
  }
  const stateName = effect.target.slice("state.".length);
  if (operation.state[stateName]?.type !== "array") {
    throw new Error(`Unreal append target "${effect.target}" is not an array`);
  }
  const value = effect.value as Record<string, unknown>;
  const arrayField = operation.state[stateName];
  if (arrayField.type !== "array") throw new Error(`Unreal append target "${effect.target}" is not an array`);
  const values = Object.keys(arrayField.items.properties)
    .map((name) => cppEffectValue(value[name], operation))
    .join(", ");
  return `    Result.State.${cppField(stateName, operation.state[stateName])}.Add({${values}});`;
}

function generateArrayElementStruct(operation: Operation, stateName: string): string {
  const operationName = pascalIdentifier(operation.id);
  const arrayField = operation.state[stateName];
  if (arrayField?.type !== "array") throw new Error(`Unreal state "${stateName}" is not an array`);
  const fields = Object.entries(arrayField.items.properties)
    .map(([name, field]) => {
      return `    ${cppType(field)} ${cppField(name, field)} = ${cppDefault(field)};`;
    })
    .join("\n");
  return `struct FCrdd${operationName}${pascalIdentifier(stateName)}Item
{
${fields}
};`;
}

function cppExpression(expression: string, operation: Operation, stateRoot: string): string {
  return expression
    .replace(/"(?:[^"\\]|\\.)*"/g, (literal) => `TEXT(${literal})`)
    .replace(/\b(?:input|state)\.[A-Za-z_][A-Za-z0-9_.]*/g, (reference) =>
      cppReference(reference, operation, stateRoot),
    );
}

function cppEffectValue(value: unknown, operation: Operation): string {
  if (typeof value === "string" && value.startsWith("$")) {
    return cppReference(value.slice(1), operation, "Result.State");
  }
  if (typeof value === "string") return `TEXT(${JSON.stringify(value)})`;
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number" && Number.isFinite(value)) return value.toString();
  throw new Error(`Unsupported Unreal append value "${JSON.stringify(value)}"`);
}

function cppReference(reference: string, operation: Operation, stateRoot: string): string {
  if (reference.startsWith("input.")) {
    const name = reference.slice("input.".length);
    const field = operation.input[name];
    if (!field) throw new Error(`Unknown Unreal input reference "${reference}"`);
    return `Input.${cppField(name, field)}`;
  }
  if (reference.startsWith("state.")) {
    const name = reference.slice("state.".length);
    const field = operation.state[name];
    if (!field) throw new Error(`Unknown Unreal state reference "${reference}"`);
    return `${stateRoot}.${cppField(name, field)}`;
  }
  throw new Error(`Unsupported Unreal reference "${reference}"`);
}

function cppField(name: string, field: FieldDefinition): string {
  const base = name.split(".").map(pascalCase).join("");
  if (field.unit === "m") return `${base}Meters`;
  if (field.unit === "JPY") return `${base}JPY`;
  return base;
}

function cppType(field: FieldDefinition): string {
  if (field.type === "number" && field.unit === "JPY") return "int64";
  if (field.type === "number") return "double";
  if (field.type === "boolean") return "bool";
  if (field.type === "string") return "FString";
  throw new Error(`Unsupported generated field type "${field.type}"`);
}

function cppDefault(field: FieldDefinition): string {
  if (field.type === "number" && field.unit === "JPY") return "0";
  if (field.type === "number") return "0.0";
  if (field.type === "boolean") return "false";
  if (field.type === "string") return 'TEXT("")';
  return "{}";
}

function traces(operation: Operation): string {
  return operation.traces.map((trace) => `// CRDD-TRACE: ${trace}`).join("\n");
}

function pascalCase(value: string): string {
  return value
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1).toLowerCase())
    .join("");
}

function pascalIdentifier(value: string): string {
  if (!/[^A-Za-z0-9]/.test(value)) {
    return value[0].toUpperCase() + value.slice(1);
  }
  return pascalCase(value);
}
