import { createHash } from "node:crypto";
import type { CrddIr, Effect, FieldDefinition, Operation } from "./model.ts";

export type GeneratedFile = {
  name: string;
  content: string;
  sha256: string;
};

export function generateUnreal(ir: CrddIr): GeneratedFile[] {
  const operation = ir.operation;
  if (operation.id !== "PlaceWall") {
    throw new Error(`Unreal MVP supports PlaceWall only, got "${operation.id}"`);
  }

  const files = [
    { name: "PlaceWall.generated.h", content: generateHeader(operation) },
    { name: "PlaceWall.generated.cpp", content: generateSource(operation) },
  ];
  return files.map((file) => ({
    ...file,
    sha256: createHash("sha256").update(file.content).digest("hex"),
  }));
}

function generateHeader(operation: Operation): string {
  const traceComment = traces(operation);
  const errorValues = operation.errors
    .map((error) => `    ${pascalCase(error.code)},`)
    .join("\n");
  const inputFields = Object.entries(operation.input)
    .map(([name, field]) => `    ${cppType(field)} ${cppField(name, field)} = ${cppDefault(field)};`)
    .join("\n");

  return `// Generated by crdd-ir. Do not edit.
${traceComment}
#pragma once

#include "CoreMinimal.h"

struct FCrddPlacedWall
{
    double LengthMeters = 0.0;
    int64 CostJPY = 0;
};

struct FCrddPlaceWallInput
{
${inputFields}
};

struct FCrddPlaceWallState
{
    int64 BudgetRemainingJPY = 0;
    TArray<FCrddPlacedWall> Walls;
};

enum class ECrddPlaceWallError : uint8
{
    None,
${errorValues}
};

struct FCrddPlaceWallResult
{
    bool bSucceeded = false;
    ECrddPlaceWallError Error = ECrddPlaceWallError::None;
    FString FailedRequirement;
    FCrddPlaceWallState State;
    TArray<FString> Traces;
};

class FCrddPlaceWallOperation
{
public:
    static FCrddPlaceWallResult Execute(
        const FCrddPlaceWallInput& Input,
        const FCrddPlaceWallState& InitialState
    );

    static FString ErrorCode(ECrddPlaceWallError Error);
};
`;
}

function generateSource(operation: Operation): string {
  const checks = operation.requires
    .map((requirement) => {
      const error = operation.errors.find((entry) => entry.code === requirement.error);
      if (!error) throw new Error(`Requirement "${requirement.id}" uses unknown error "${requirement.error}"`);
      return `    // ${requirement.id}: ${requirement.expression}
    if (!(${cppExpression(requirement.expression, operation, "InitialState")}))
    {
        return Failure(
            ECrddPlaceWallError::${pascalCase(requirement.error)},
            TEXT("${requirement.id}"),
            InitialState,
            {${error.traces.map((trace) => `TEXT("${trace}")`).join(", ")}}
        );
    }`;
    })
    .join("\n\n");

  const effects = operation.effects.map((effect) => cppEffect(effect, operation)).join("\n");
  const successTraces = operation.traces.map((trace) => `TEXT("${trace}")`).join(", ");
  const errorCases = operation.errors
    .map(
      (error) => `    case ECrddPlaceWallError::${pascalCase(error.code)}:
        return TEXT("${error.code}");`,
    )
    .join("\n");

  return `// Generated by crdd-ir. Do not edit.
${traces(operation)}
#include "Generated/PlaceWall.generated.h"

#include <initializer_list>

namespace
{
FCrddPlaceWallResult Failure(
    ECrddPlaceWallError Error,
    const TCHAR* FailedRequirement,
    const FCrddPlaceWallState& InitialState,
    std::initializer_list<const TCHAR*> FailureTraces
)
{
    FCrddPlaceWallResult Result;
    Result.Error = Error;
    Result.FailedRequirement = FailedRequirement;
    Result.State = InitialState;
    for (const TCHAR* Trace : FailureTraces)
    {
        Result.Traces.Add(Trace);
    }
    return Result;
}
}

FCrddPlaceWallResult FCrddPlaceWallOperation::Execute(
    const FCrddPlaceWallInput& Input,
    const FCrddPlaceWallState& InitialState
)
{
${checks}

    FCrddPlaceWallResult Result;
    Result.bSucceeded = true;
    Result.State = InitialState;
${effects}
    Result.Traces = {${successTraces}};
    return Result;
}

FString FCrddPlaceWallOperation::ErrorCode(ECrddPlaceWallError Error)
{
    switch (Error)
    {
    case ECrddPlaceWallError::None:
        return TEXT("");
${errorCases}
    default:
        return TEXT("UNKNOWN");
    }
}
`;
}

function cppEffect(effect: Effect, operation: Operation): string {
  if (effect.action === "assign") {
    return `    ${cppReference(effect.target, operation, "Result.State")} = ${cppExpression(
      effect.expression,
      operation,
      "Result.State",
    )};`;
  }

  if (effect.target !== "state.walls" || typeof effect.value !== "object" || effect.value === null) {
    throw new Error("Unreal MVP only supports object append to state.walls");
  }
  const value = effect.value as Record<string, unknown>;
  const length = value.length;
  const cost = value.cost;
  if (length !== "$input.length" || cost !== "$input.cost") {
    throw new Error("Unreal MVP PlaceWall append requires length and cost input references");
  }
  return "    Result.State.Walls.Add({Input.LengthMeters, Input.CostJPY});";
}

function cppExpression(expression: string, operation: Operation, stateRoot: string): string {
  return expression.replace(/\b(?:input|state)\.[A-Za-z_][A-Za-z0-9_.]*/g, (reference) =>
    cppReference(reference, operation, stateRoot),
  );
}

function cppReference(reference: string, operation: Operation, stateRoot: string): string {
  if (reference.startsWith("input.")) {
    const name = reference.slice("input.".length);
    const field = operation.input[name];
    if (!field) throw new Error(`Unknown Unreal input reference "${reference}"`);
    return `Input.${cppField(name, field)}`;
  }
  if (reference.startsWith("state.")) {
    const name = reference.slice("state.".length);
    const field = operation.state[name];
    if (!field) throw new Error(`Unknown Unreal state reference "${reference}"`);
    return `${stateRoot}.${cppField(name, field)}`;
  }
  throw new Error(`Unsupported Unreal reference "${reference}"`);
}

function cppField(name: string, field: FieldDefinition): string {
  const base = name.split(".").map(pascalCase).join("");
  if (field.unit === "m") return `${base}Meters`;
  if (field.unit === "JPY") return `${base}JPY`;
  return base;
}

function cppType(field: FieldDefinition): string {
  if (field.type === "number" && field.unit === "JPY") return "int64";
  if (field.type === "number") return "double";
  if (field.type === "boolean") return "bool";
  if (field.type === "string") return "FString";
  throw new Error(`Unsupported generated field type "${field.type}"`);
}

function cppDefault(field: FieldDefinition): string {
  if (field.type === "number" && field.unit === "JPY") return "0";
  if (field.type === "number") return "0.0";
  if (field.type === "boolean") return "false";
  if (field.type === "string") return 'TEXT("")';
  return "{}";
}

function traces(operation: Operation): string {
  return operation.traces.map((trace) => `// CRDD-TRACE: ${trace}`).join("\n");
}

function pascalCase(value: string): string {
  return value
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1).toLowerCase())
    .join("");
}
