import { createHash } from "node:crypto";
import type { GeneratedFile } from "./unreal.ts";
import type { UnrealDeclaration, UnrealTargetPlan } from "./unreal-target.ts";

export function generateUnrealReflection(plan: UnrealTargetPlan): GeneratedFile[] {
  return plan.adapter.declarations.map((declaration) => {
    const name = `${declaration.name}.generated-adapter.h`;
    const content = renderDeclaration(declaration, name);
    return {
      name,
      content,
      sha256: createHash("sha256").update(content).digest("hex"),
    };
  });
}

function renderDeclaration(declaration: UnrealDeclaration, fileName: string): string {
  const generatedInclude = fileName.replace(/\.h$/, ".generated.h");
  const metadata = renderMetadata(declaration.metadata);
  const macro = metadata ? `${declaration.kind}(${metadata})` : `${declaration.kind}()`;
  const includes = [
    '#include "CoreMinimal.h"',
    ...(declaration.kind === "UINTERFACE" ? ['#include "UObject/Interface.h"'] : []),
    `#include "${generatedInclude}"`,
  ].join("\n");
  if (declaration.kind === "UENUM") {
    return `// Generated by crdd-ir. Do not edit.
#pragma once

${includes}

${macro}
enum class ${declaration.name} : uint8
{
${(declaration.values ?? []).map((value) => `    ${value},`).join("\n")}
};
`;
  }
  if (declaration.kind === "UINTERFACE") {
    const interfaceName = declaration.name.startsWith("U")
      ? `I${declaration.name.slice(1)}`
      : `I${declaration.name}`;
    const functions = declaration.functions.map((fn) => {
      const fnMetadata = renderMetadata(fn.metadata);
      const specifiers = [...fn.specifiers, ...(fnMetadata ? [`meta=(${fnMetadata})`] : [])];
      const parameters = fn.parameters.map((parameter) =>
        `${parameter.cppType} ${parameter.name}`
      ).join(", ");
      return `    UFUNCTION(${specifiers.join(", ")})\n` +
        `    ${fn.returnType} ${fn.name}(${parameters});`;
    }).join("\n\n");
    return `// Generated by crdd-ir. Do not edit.
#pragma once

${includes}

${macro}
class ${declaration.apiMacro} ${declaration.name} : public UInterface
{
    GENERATED_BODY()
};

class ${declaration.apiMacro} ${interfaceName}
{
    GENERATED_BODY()

public:
${functions}
};
`;
  }
  const base = declaration.base ?? (
    declaration.kind === "UCLASS"
      ? "UObject"
      : declaration.kind === "UINTERFACE"
        ? "UInterface"
        : undefined
  );
  const properties = declaration.properties.map((property) =>
    `    UPROPERTY(${property.specifiers.join(", ")})\n` +
    `    ${property.cppType} ${property.name};`
  ).join("\n\n");
  const functions = declaration.functions.map((fn) => {
    const fnMetadata = renderMetadata(fn.metadata);
    const specifiers = [...fn.specifiers, ...(fnMetadata ? [`meta=(${fnMetadata})`] : [])];
    return `    UFUNCTION(${specifiers.join(", ")})\n` +
      `    ${fn.returnType} ${fn.name}(${fn.parameters.map((parameter) =>
        `${parameter.cppType} ${parameter.name}`
      ).join(", ")});`;
  }).join("\n\n");
  const classKeyword = declaration.kind === "USTRUCT" ? "struct" : "class";
  const inheritance = base ? ` : public ${base}` : "";
  return `// Generated by crdd-ir. Do not edit.
#pragma once

${includes}

${macro}
${classKeyword} ${declaration.apiMacro} ${declaration.name}${inheritance}
{
    GENERATED_BODY()

public:
${[properties, functions].filter(Boolean).join("\n\n")}
};
`;
}

function renderMetadata(metadata: Record<string, string | boolean | number>): string {
  return Object.entries(metadata).sort(([a], [b]) => a.localeCompare(b))
    .map(([key, value]) =>
      typeof value === "boolean"
        ? (value ? key : `${key}=false`)
        : `${key}=${JSON.stringify(String(value))}`
    )
    .join(", ");
}
