import type { Operation } from "./model.ts";

export type UnrealBridgeFile = {
  name: string;
  content: string;
};

export function generateUnrealBridge(operation: Operation): UnrealBridgeFile[] {
  const operationName = pascalIdentifier(operation.id);
  return [
    {
      name: `${operationName}.bridge.generated.h`,
      content: generateHeader(operationName),
    },
    {
      name: `${operationName}.bridge.generated.cpp`,
      content: generateSource(operationName),
    },
    {
      name: `${operationName}.bridge.generated.spec.cpp`,
      content: generateFixture(operationName),
    },
  ];
}

function generateHeader(operationName: string): string {
  return `// Generated by crdd-ir. Do not edit.
#pragma once

#include "${operationName}.generated.h"

enum class ECrdd${operationName}BridgeFailure : uint8
{
    None,
    RequestMapping,
    SnapshotLoad,
    Contract,
    RevisionOverflow,
    Commit
};

struct FCrdd${operationName}BridgeRequestDto
{
    FCrdd${operationName}Input Input;
};

struct FCrdd${operationName}BridgeSnapshotDto
{
    FCrdd${operationName}State State;
    uint64 Revision = 0;
};

struct FCrdd${operationName}BridgeErrorDto
{
    ECrdd${operationName}BridgeFailure Failure =
        ECrdd${operationName}BridgeFailure::None;
    FString Code;
    FString Diagnostic;
    FString FailedRequirement;
    TArray<FString> Traces;
};

struct FCrdd${operationName}BridgeResultDto
{
    bool bSucceeded = false;
    FCrdd${operationName}BridgeSnapshotDto Snapshot;
    FCrdd${operationName}BridgeErrorDto Error;
};

// Product code owns domain/World conversion and durable persistence.
// CommitSnapshot must atomically compare ExpectedRevision and publish Candidate.
class ICrdd${operationName}ProductAdapter
{
public:
    virtual ~ICrdd${operationName}ProductAdapter() = default;

    virtual bool BuildRequest(
        FCrdd${operationName}BridgeRequestDto& OutRequest,
        FString& OutDiagnostic
    ) = 0;

    virtual bool LoadSnapshot(
        FCrdd${operationName}BridgeSnapshotDto& OutSnapshot,
        FString& OutDiagnostic
    ) = 0;

    virtual bool CommitSnapshot(
        const FCrdd${operationName}BridgeSnapshotDto& Candidate,
        uint64 ExpectedRevision,
        FString& OutDiagnostic
    ) = 0;
};

class FCrdd${operationName}Bridge
{
public:
    // Contract failures and adapter failures return the loaded snapshot unchanged.
    // CommitSnapshot is called only after the generated contract succeeds.
    static FCrdd${operationName}BridgeResultDto Execute(
        ICrdd${operationName}ProductAdapter& Adapter
    );
};
`;
}

function generateSource(operationName: string): string {
  return `// Generated by crdd-ir. Do not edit.
#include "${operationName}.bridge.generated.h"

#include <limits>

namespace
{
FCrdd${operationName}BridgeResultDto BridgeFailure(
    ECrdd${operationName}BridgeFailure Failure,
    const FString& Code,
    const FString& Diagnostic,
    const FCrdd${operationName}BridgeSnapshotDto& OriginalSnapshot
)
{
    FCrdd${operationName}BridgeResultDto Result;
    Result.Snapshot = OriginalSnapshot;
    Result.Error.Failure = Failure;
    Result.Error.Code = Code;
    Result.Error.Diagnostic = Diagnostic;
    return Result;
}
}

FCrdd${operationName}BridgeResultDto FCrdd${operationName}Bridge::Execute(
    ICrdd${operationName}ProductAdapter& Adapter
)
{
    FCrdd${operationName}BridgeRequestDto Request;
    FString Diagnostic;
    if (!Adapter.BuildRequest(Request, Diagnostic))
    {
        return BridgeFailure(
            ECrdd${operationName}BridgeFailure::RequestMapping,
            TEXT("BRIDGE_REQUEST_MAPPING"),
            Diagnostic,
            {}
        );
    }

    FCrdd${operationName}BridgeSnapshotDto OriginalSnapshot;
    Diagnostic.Reset();
    if (!Adapter.LoadSnapshot(OriginalSnapshot, Diagnostic))
    {
        return BridgeFailure(
            ECrdd${operationName}BridgeFailure::SnapshotLoad,
            TEXT("BRIDGE_SNAPSHOT_LOAD"),
            Diagnostic,
            OriginalSnapshot
        );
    }

    const FCrdd${operationName}Result ContractResult =
        FCrdd${operationName}Operation::Execute(Request.Input, OriginalSnapshot.State);
    if (!ContractResult.bSucceeded)
    {
        FCrdd${operationName}BridgeResultDto Result = BridgeFailure(
            ECrdd${operationName}BridgeFailure::Contract,
            FCrdd${operationName}Operation::ErrorCode(ContractResult.Error),
            TEXT(""),
            OriginalSnapshot
        );
        Result.Error.FailedRequirement = ContractResult.FailedRequirement;
        Result.Error.Traces = ContractResult.Traces;
        return Result;
    }

    if (OriginalSnapshot.Revision == std::numeric_limits<uint64>::max())
    {
        return BridgeFailure(
            ECrdd${operationName}BridgeFailure::RevisionOverflow,
            TEXT("BRIDGE_REVISION_OVERFLOW"),
            TEXT("Snapshot revision cannot be incremented."),
            OriginalSnapshot
        );
    }

    FCrdd${operationName}BridgeSnapshotDto Candidate = OriginalSnapshot;
    Candidate.State = ContractResult.State;
    Candidate.Revision = OriginalSnapshot.Revision + 1;
    Diagnostic.Reset();
    if (!Adapter.CommitSnapshot(Candidate, OriginalSnapshot.Revision, Diagnostic))
    {
        return BridgeFailure(
            ECrdd${operationName}BridgeFailure::Commit,
            TEXT("BRIDGE_COMMIT"),
            Diagnostic,
            OriginalSnapshot
        );
    }

    FCrdd${operationName}BridgeResultDto Result;
    Result.bSucceeded = true;
    Result.Snapshot = Candidate;
    return Result;
}
`;
}

function generateFixture(operationName: string): string {
  return `// Generated by crdd-ir. Do not edit.
#if WITH_DEV_AUTOMATION_TESTS

#include "${operationName}.bridge.generated.h"

#include "Misc/AutomationTest.h"

namespace
{
class FCrdd${operationName}FailingAdapter final
    : public ICrdd${operationName}ProductAdapter
{
public:
    bool bRequestSucceeds = false;
    bool bLoadSucceeds = false;
    int32 CommitCalls = 0;

    virtual bool BuildRequest(
        FCrdd${operationName}BridgeRequestDto& OutRequest,
        FString& OutDiagnostic
    ) override
    {
        OutDiagnostic = TEXT("request mapping rejected");
        return bRequestSucceeds;
    }

    virtual bool LoadSnapshot(
        FCrdd${operationName}BridgeSnapshotDto& OutSnapshot,
        FString& OutDiagnostic
    ) override
    {
        OutSnapshot.Revision = 41;
        OutDiagnostic = TEXT("snapshot load rejected");
        return bLoadSucceeds;
    }

    virtual bool CommitSnapshot(
        const FCrdd${operationName}BridgeSnapshotDto& Candidate,
        uint64 ExpectedRevision,
        FString& OutDiagnostic
    ) override
    {
        ++CommitCalls;
        return false;
    }
};
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
    FCrdd${operationName}BridgeAtomicFailureTest,
    "CRDD.${operationName}.Bridge.AtomicFailure.Generated",
    EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter
)

bool FCrdd${operationName}BridgeAtomicFailureTest::RunTest(const FString& Parameters)
{
    FCrdd${operationName}FailingAdapter Adapter;
    const FCrdd${operationName}BridgeResultDto MappingFailure =
        FCrdd${operationName}Bridge::Execute(Adapter);
    TestFalse(TEXT("Request mapping failure is reported"), MappingFailure.bSucceeded);
    TestEqual(TEXT("Request failure does not commit"), Adapter.CommitCalls, 0);

    Adapter.bRequestSucceeds = true;
    const FCrdd${operationName}BridgeResultDto LoadFailure =
        FCrdd${operationName}Bridge::Execute(Adapter);
    TestFalse(TEXT("Snapshot load failure is reported"), LoadFailure.bSucceeded);
    TestEqual(TEXT("Loaded revision is preserved"), LoadFailure.Snapshot.Revision, uint64(41));
    TestEqual(TEXT("Snapshot load failure does not commit"), Adapter.CommitCalls, 0);
    return true;
}

#endif
`;
}

function pascalIdentifier(value: string): string {
  if (!/[^A-Za-z0-9]/.test(value)) {
    return value[0].toUpperCase() + value.slice(1);
  }
  return value
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1).toLowerCase())
    .join("");
}
